In [1]:
import requests
import pandas as pd
import time

In [2]:
url = "https://api.deezer.com/search/artist"
params = {"q": "Queen"}

response = requests.get(url, params=params)

print(response.status_code)

200

In [3]:
data = response.json()

type(data)

dict

In [4]:
data.keys()

dict_keys(['data', 'total', 'next'])

In [ ]:
# data - donde vienen los artistas
# total - cantidad total de resultados
# next - ver mas resultados/paginación

In [5]:
data["data"]

[{'id': 412,
  'name': 'Queen',
  'link': 'https://www.deezer.com/artist/412',
  'picture': 'https://api.deezer.com/artist/412/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/71eeb9e2eeb375df35a3c0654a5a01ab/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/71eeb9e2eeb375df35a3c0654a5a01ab/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/71eeb9e2eeb375df35a3c0654a5a01ab/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/71eeb9e2eeb375df35a3c0654a5a01ab/1000x1000-000000-80-0-0.jpg',
  'nb_album': 80,
  'nb_fan': 12703373,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/412/top?limit=50',
  'type': 'artist'},
 {'id': 1177,
  'name': 'Queens of the Stone Age',
  'link': 'https://www.deezer.com/artist/1177',
  'picture': 'https://api.deezer.com/artist/1177/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/59574e8a87b293aa74f9201d0b83e58a/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/59574e8a87b293aa74f9201d0b83e58a/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/59574e8a87b293aa74f9201d0b83e58a/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/59574e8a87b293aa74f9201d0b83e58a/1000x1000-000000-80-0-0.jpg',
  'nb_album': 25,
  'nb_fan': 1357142,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/1177/top?limit=50',
  'type': 'artist'},
 {'id': 141954732,
  'name': 'Queen',
  'link': 'https://www.deezer.com/artist/141954732',
  'picture': 'https://api.deezer.com/artist/141954732/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/d41d8cd98f00b204e9800998ecf8427e/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/d41d8cd98f00b204e9800998ecf8427e/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/d41d8cd98f00b204e9800998ecf8427e/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/d41d8cd98f00b204e9800998ecf8427e/1000x1000-000000-80-0-0.jpg',
  'nb_album': 23,
  'nb_fan': 380,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/141954732/top?limit=50',
  'type': 'artist'},
 {'id': 135041032,
  'name': 'Queen(Ares)',
  'link': 'https://www.deezer.com/artist/135041032',
  'picture': 'https://api.deezer.com/artist/135041032/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/a131ced363dd67249e6a9167164188cb/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/a131ced363dd67249e6a9167164188cb/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/a131ced363dd67249e6a9167164188cb/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/a131ced363dd67249e6a9167164188cb/1000x1000-000000-80-0-0.jpg',
  'nb_album': 3,
  'nb_fan': 129,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/135041032/top?limit=50',
  'type': 'artist'},
 {'id': 61045802,
  'name': 'Queen',
  'link': 'https://www.deezer.com/artist/61045802',
  'picture': 'https://api.deezer.com/artist/61045802/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/06188edd60dc4b04a5520a3a75a1059a/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/06188edd60dc4b04a5520a3a75a1059a/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/06188edd60dc4b04a5520a3a75a1059a/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/06188edd60dc4b04a5520a3a75a1059a/1000x1000-000000-80-0-0.jpg',
  'nb_album': 5,
  'nb_fan': 44,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/61045802/top?limit=50',
  'type': 'artist'},
 {'id': 268175642,
  'name': 'Queen',
  'link': 'https://www.deezer.com/artist/268175642',
  'picture': 'https://api.deezer.com/artist/268175642/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/eb41ddbc505b7c7e68d5d81a4be8c7f7/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/eb41ddbc505b7c7e68d5d81a4be8c7f7/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/eb41ddbc505b7c7e68d5d81a4be8c7f7/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/eb41ddbc505b7c7e68d5d81a4be8c7f7/1000x1000-000000-80-0-0.jpg',
  'nb_album': 2,
  'nb_fan': 3,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/268175642/top?limit=50',
  'type': 'artist'},
 {'id': 164525067,
  'name': 'Queen D',
  'link': 'https://www.deezer.com/artist/164525067',
  'picture': 'https://api.deezer.com/artist/164525067/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/fcfe26ebb3013221e330f904f0145b96/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/fcfe26ebb3013221e330f904f0145b96/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/fcfe26ebb3013221e330f904f0145b96/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/fcfe26ebb3013221e330f904f0145b96/1000x1000-000000-80-0-0.jpg',
  'nb_album': 24,
  'nb_fan': 744,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/164525067/top?limit=50',
  'type': 'artist'},
 {'id': 8723,
  'name': 'Queen Omega',
  'link': 'https://www.deezer.com/artist/8723',
  'picture': 'https://api.deezer.com/artist/8723/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/6a6f9c1724b7ee46379c515eab3f54d9/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/6a6f9c1724b7ee46379c515eab3f54d9/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/6a6f9c1724b7ee46379c515eab3f54d9/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/6a6f9c1724b7ee46379c515eab3f54d9/1000x1000-000000-80-0-0.jpg',
  'nb_album': 39,
  'nb_fan': 35769,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/8723/top?limit=50',
  'type': 'artist'},
 {'id': 85704202,
  'name': 'Josiah Queen',
  'link': 'https://www.deezer.com/artist/85704202',
  'picture': 'https://api.deezer.com/artist/85704202/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/909d5729a35315d3550d211027312638/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/909d5729a35315d3550d211027312638/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/909d5729a35315d3550d211027312638/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/909d5729a35315d3550d211027312638/1000x1000-000000-80-0-0.jpg',
  'nb_album': 34,
  'nb_fan': 9384,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/85704202/top?limit=50',
  'type': 'artist'},
 {'id': 7958,
  'name': 'Queen Latifah',
  'link': 'https://www.deezer.com/artist/7958',
  'picture': 'https://api.deezer.com/artist/7958/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/e9f9ccf19562951e753be4a69899fc11/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/e9f9ccf19562951e753be4a69899fc11/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/e9f9ccf19562951e753be4a69899fc11/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/e9f9ccf19562951e753be4a69899fc11/1000x1000-000000-80-0-0.jpg',
  'nb_album': 11,
  'nb_fan': 68821,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/7958/top?limit=50',
  'type': 'artist'},
 {'id': 13895003,
  'name': 'Queen Naija',
  'link': 'https://www.deezer.com/artist/13895003',
  'picture': 'https://api.deezer.com/artist/13895003/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/62d42cec595373a0ca9ae0de3794721e/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/62d42cec595373a0ca9ae0de3794721e/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/62d42cec595373a0ca9ae0de3794721e/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/62d42cec595373a0ca9ae0de3794721e/1000x1000-000000-80-0-0.jpg',
  'nb_album': 41,
  'nb_fan': 116576,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/13895003/top?limit=50',
  'type': 'artist'},
 {'id': 187156157,
  'name': 'Queen Bee',
  'link': 'https://www.deezer.com/artist/187156157',
  'picture': 'https://api.deezer.com/artist/187156157/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/ab3a5f753fe481171a8a4fa7bd46fdb2/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/ab3a5f753fe481171a8a4fa7bd46fdb2/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/ab3a5f753fe481171a8a4fa7bd46fdb2/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/ab3a5f753fe481171a8a4fa7bd46fdb2/1000x1000-000000-80-0-0.jpg',
  'nb_album': 51,
  'nb_fan': 3958,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/187156157/top?limit=50',
  'type': 'artist'},
 {'id': 61326,
  'name': 'Queen Ifrica',
  'link': 'https://www.deezer.com/artist/61326',
  'picture': 'https://api.deezer.com/artist/61326/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/c11e9dd36429be806b6a6359a74207f1/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/c11e9dd36429be806b6a6359a74207f1/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/c11e9dd36429be806b6a6359a74207f1/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/c11e9dd36429be806b6a6359a74207f1/1000x1000-000000-80-0-0.jpg',
  'nb_album': 8,
  'nb_fan': 36681,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/61326/top?limit=50',
  'type': 'artist'},
 {'id': 13183243,
  'name': 'Queen Millz',
  'link': 'https://www.deezer.com/artist/13183243',
  'picture': 'https://api.deezer.com/artist/13183243/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/141506e400836a7ffc78575624655a93/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/141506e400836a7ffc78575624655a93/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/141506e400836a7ffc78575624655a93/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/141506e400836a7ffc78575624655a93/1000x1000-000000-80-0-0.jpg',
  'nb_album': 36,
  'nb_fan': 194,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/13183243/top?limit=50',
  'type': 'artist'},
 {'id': 1347936,
  'name': 'Queen House',
  'link': 'https://www.deezer.com/artist/1347936',
  'picture': 'https://api.deezer.com/artist/1347936/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/4c2001c5468d65279866e51631275ada/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/4c2001c5468d65279866e51631275ada/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/4c2001c5468d65279866e51631275ada/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/4c2001c5468d65279866e51631275ada/1000x1000-000000-80-0-0.jpg',
  'nb_album': 1,
  'nb_fan': 819,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/1347936/top?limit=50',
  'type': 'artist'},
 {'id': 4747571,
  'name': 'Queen Victoria',
  'link': 'https://www.deezer.com/artist/4747571',
  'picture': 'https://api.deezer.com/artist/4747571/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/9115bdcf9dd4e3edab4304044ddf5049/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/9115bdcf9dd4e3edab4304044ddf5049/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/9115bdcf9dd4e3edab4304044ddf5049/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/9115bdcf9dd4e3edab4304044ddf5049/1000x1000-000000-80-0-0.jpg',
  'nb_album': 20,
  'nb_fan': 8,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/4747571/top?limit=50',
  'type': 'artist'},
 {'id': 130285512,
  'name': 'Scene Queen',
  'link': 'https://www.deezer.com/artist/130285512',
  'picture': 'https://api.deezer.com/artist/130285512/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/b83fbaaaed873d4a368fd3bfab915b16/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/b83fbaaaed873d4a368fd3bfab915b16/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/b83fbaaaed873d4a368fd3bfab915b16/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/b83fbaaaed873d4a368fd3bfab915b16/1000x1000-000000-80-0-0.jpg',
  'nb_album': 21,
  'nb_fan': 6941,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/130285512/top?limit=50',
  'type': 'artist'},
 {'id': 14607747,
  'name': 'Afro Queen',
  'link': 'https://www.deezer.com/artist/14607747',
  'picture': 'https://api.deezer.com/artist/14607747/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/09873a1b8c00d28f4d7474af6f98ada4/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/09873a1b8c00d28f4d7474af6f98ada4/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/09873a1b8c00d28f4d7474af6f98ada4/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/09873a1b8c00d28f4d7474af6f98ada4/1000x1000-000000-80-0-0.jpg',
  'nb_album': 202,
  'nb_fan': 85,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/14607747/top?limit=50',
  'type': 'artist'},
 {'id': 9019,
  'name': 'Ivy Queen',
  'link': 'https://www.deezer.com/artist/9019',
  'picture': 'https://api.deezer.com/artist/9019/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/b580cce5db9caa748ae7f48b7d0b081c/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/b580cce5db9caa748ae7f48b7d0b081c/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/b580cce5db9caa748ae7f48b7d0b081c/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/b580cce5db9caa748ae7f48b7d0b081c/1000x1000-000000-80-0-0.jpg',
  'nb_album': 61,
  'nb_fan': 127367,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/9019/top?limit=50',
  'type': 'artist'},
 {'id': 5244141,
  'name': 'Baby Queen',
  'link': 'https://www.deezer.com/artist/5244141',
  'picture': 'https://api.deezer.com/artist/5244141/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/832c9cae12afa6b759fa1e37f0de66c3/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/832c9cae12afa6b759fa1e37f0de66c3/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/832c9cae12afa6b759fa1e37f0de66c3/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/832c9cae12afa6b759fa1e37f0de66c3/1000x1000-000000-80-0-0.jpg',
  'nb_album': 32,
  'nb_fan': 5386,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/5244141/top?limit=50',
  'type': 'artist'},
 {'id': 450477,
  'name': 'Queen Pen',
  'link': 'https://www.deezer.com/artist/450477',
  'picture': 'https://api.deezer.com/artist/450477/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/6ab28f73843e4ef88028a8bfad2d3500/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/6ab28f73843e4ef88028a8bfad2d3500/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/6ab28f73843e4ef88028a8bfad2d3500/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/6ab28f73843e4ef88028a8bfad2d3500/1000x1000-000000-80-0-0.jpg',
  'nb_album': 4,
  'nb_fan': 1035,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/450477/top?limit=50',
  'type': 'artist'},
 {'id': 10935732,
  'name': 'Queen Key',
  'link': 'https://www.deezer.com/artist/10935732',
  'picture': 'https://api.deezer.com/artist/10935732/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/135a3490c06d8602bf6f4153a8509cf1/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/135a3490c06d8602bf6f4153a8509cf1/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/135a3490c06d8602bf6f4153a8509cf1/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/135a3490c06d8602bf6f4153a8509cf1/1000x1000-000000-80-0-0.jpg',
  'nb_album': 82,
  'nb_fan': 2158,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/10935732/top?limit=50',
  'type': 'artist'},
 {'id': 826043,
  'name': 'Storm Queen',
  'link': 'https://www.deezer.com/artist/826043',
  'picture': 'https://api.deezer.com/artist/826043/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/5799050a459fbae86225f4e7df87bc47/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/5799050a459fbae86225f4e7df87bc47/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/5799050a459fbae86225f4e7df87bc47/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/5799050a459fbae86225f4e7df87bc47/1000x1000-000000-80-0-0.jpg',
  'nb_album': 14,
  'nb_fan': 123218,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/826043/top?limit=50',
  'type': 'artist'},
 {'id': 70649872,
  'name': 'Grag Queen',
  'link': 'https://www.deezer.com/artist/70649872',
  'picture': 'https://api.deezer.com/artist/70649872/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/d45f9a84a9845bea14007f40c98f121b/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/d45f9a84a9845bea14007f40c98f121b/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/d45f9a84a9845bea14007f40c98f121b/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/d45f9a84a9845bea14007f40c98f121b/1000x1000-000000-80-0-0.jpg',
  'nb_album': 40,
  'nb_fan': 15156,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/70649872/top?limit=50',
  'type': 'artist'},
 {'id': 1730,
  'name': 'Queen Adreena',
  'link': 'https://www.deezer.com/artist/1730',
  'picture': 'https://api.deezer.com/artist/1730/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/1829eb51740b716580c6a503162782cd/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/1829eb51740b716580c6a503162782cd/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/1829eb51740b716580c6a503162782cd/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/1829eb51740b716580c6a503162782cd/1000x1000-000000-80-0-0.jpg',
  'nb_album': 9,
  'nb_fan': 4966,
  'radio': True,
  'tracklist': 'https://api.deezer.com/artist/1730/top?limit=50',
  'type': 'artist'}]

In [6]:
type(data["data"])

list

In [7]:
df_artistas = pd.DataFrame(data["data"])

df_artistas.head()

,id,name,link,picture,picture_small,picture_medium,picture_big,picture_xl,nb_album,nb_fan,radio,tracklist,type
0,412,Queen,https://www.deezer.com/artist/412,https://api.deezer.com/artist/412/image,https://cdn-images.dzcdn.net/images/artist/71e...,https://cdn-images.dzcdn.net/images/artist/71e...,https://cdn-images.dzcdn.net/images/artist/71e...,https://cdn-images.dzcdn.net/images/artist/71e...,80,12703373,True,https://api.deezer.com/artist/412/top?limit=50,artist
1,1177,Queens of the Stone Age,https://www.deezer.com/artist/1177,https://api.deezer.com/artist/1177/image,https://cdn-images.dzcdn.net/images/artist/595...,https://cdn-images.dzcdn.net/images/artist/595...,https://cdn-images.dzcdn.net/images/artist/595...,https://cdn-images.dzcdn.net/images/artist/595...,25,1357142,True,https://api.deezer.com/artist/1177/top?limit=50,artist
2,141954732,Queen,https://www.deezer.com/artist/141954732,https://api.deezer.com/artist/141954732/image,https://cdn-images.dzcdn.net/images/artist/d41...,https://cdn-images.dzcdn.net/images/artist/d41...,https://cdn-images.dzcdn.net/images/artist/d41...,https://cdn-images.dzcdn.net/images/artist/d41...,23,380,True,https://api.deezer.com/artist/141954732/top?li...,artist
3,135041032,Queen(Ares),https://www.deezer.com/artist/135041032,https://api.deezer.com/artist/135041032/image,https://cdn-images.dzcdn.net/images/artist/a13...,https://cdn-images.dzcdn.net/images/artist/a13...,https://cdn-images.dzcdn.net/images/artist/a13...,https://cdn-images.dzcdn.net/images/artist/a13...,3,129,True,https://api.deezer.com/artist/135041032/top?li...,artist
4,61045802,Queen,https://www.deezer.com/artist/61045802,https://api.deezer.com/artist/61045802/image,https://cdn-images.dzcdn.net/images/artist/061...,https://cdn-images.dzcdn.net/images/artist/061...,https://cdn-images.dzcdn.net/images/artist/061...,https://cdn-images.dzcdn.net/images/artist/061...,5,44,True,https://api.deezer.com/artist/61045802/top?lim...,artist

In [8]:
df_artistas.columns

Index(['id', 'name', 'link', 'picture', 'picture_small', 'picture_medium',
       'picture_big', 'picture_xl', 'nb_album', 'nb_fan', 'radio', 'tracklist',
       'type'],
      dtype='str')

In [9]:
df_artistas = df_artistas[["id", "name"]]

df_artistas.head()

          id                     name
0        412                    Queen
1       1177  Queens of the Stone Age
2  141954732                    Queen
3  135041032              Queen(Ares)
4   61045802                    Queen

In [10]:
df_artistas.iloc[0]

id        412
name    Queen
Name: 0, dtype: object

In [11]:
artist_id = df_artistas.iloc[0]["id"]

artist_id

np.int64(412)

In [12]:
url_top_tracks = f"https://api.deezer.com/artist/{artist_id}/top"

url_top_tracks

'https://api.deezer.com/artist/412/top'

In [13]:
response_tracks = requests.get(url_top_tracks)

data_tracks = response_tracks.json()

data_tracks.keys()

dict_keys(['data', 'total', 'next'])

In [14]:
df_tracks = pd.DataFrame(data_tracks["data"])

df_tracks.head()

,id,readable,title,title_short,title_version,link,duration,rank,explicit_lyrics,explicit_content_lyrics,explicit_content_cover,preview,contributors,md5_image,artist,album,type
0,12206946,True,Another One Bites The Dust (Remastered 2011),Another One Bites The Dust,(Remastered 2011),https://www.deezer.com/track/12206946,217,939107,False,0,0,https://cdnt-preview.dzcdn.net/api/1/1/3/e/4/0...,"[{'id': 412, 'name': 'Queen', 'link': 'https:/...",9a20f8b2547cbb74635539c219de3a84,"{'id': 412, 'name': 'Queen', 'tracklist': 'htt...","{'id': 1121182, 'title': 'The Game (2011 Remas...",track
1,9997018,True,Bohemian Rhapsody (Remastered 2011),Bohemian Rhapsody,(Remastered 2011),https://www.deezer.com/track/9997018,354,959624,False,0,0,https://cdnt-preview.dzcdn.net/api/1/1/e/3/9/0...,"[{'id': 412, 'name': 'Queen', 'link': 'https:/...",6706f1154083f461a348508c28030a30,"{'id': 412, 'name': 'Queen', 'tracklist': 'htt...","{'id': 915785, 'title': 'A Night At The Opera ...",track
2,12209331,True,Don't Stop Me Now (Remastered 2011),Don't Stop Me Now,(Remastered 2011),https://www.deezer.com/track/12209331,212,949599,False,0,0,https://cdnt-preview.dzcdn.net/api/1/1/4/2/4/0...,"[{'id': 412, 'name': 'Queen', 'link': 'https:/...",fb22a75aa1aafc992230abd0bd79faef,"{'id': 412, 'name': 'Queen', 'tracklist': 'htt...","{'id': 1121401, 'title': 'Jazz (2011 Remaster)...",track
3,12274786,True,Under Pressure (Remastered 2011),Under Pressure,(Remastered 2011),https://www.deezer.com/track/12274786,247,926707,False,0,0,https://cdnt-preview.dzcdn.net/api/1/1/e/7/2/0...,"[{'id': 412, 'name': 'Queen', 'link': 'https:/...",e16455433a84c7e19025403ae3eec52d,"{'id': 412, 'name': 'Queen', 'tracklist': 'htt...","{'id': 1127912, 'title': 'Hot Space (Deluxe Ed...",track
4,7868649,True,Radio Ga Ga (Remastered 2011),Radio Ga Ga,(Remastered 2011),https://www.deezer.com/track/7868649,343,837120,False,0,0,https://cdnt-preview.dzcdn.net/api/1/1/e/5/7/0...,"[{'id': 412, 'name': 'Queen', 'link': 'https:/...",fa63381faefb51fba501498bc836765a,"{'id': 412, 'name': 'Queen', 'tracklist': 'htt...","{'id': 726319, 'title': 'Greatest Hits II (201...",track

In [15]:
df_tracks.columns

Index(['id', 'readable', 'title', 'title_short', 'title_version', 'link',
       'duration', 'rank', 'explicit_lyrics', 'explicit_content_lyrics',
       'explicit_content_cover', 'preview', 'contributors', 'md5_image',
       'artist', 'album', 'type'],
      dtype='str')

In [16]:
df_tracks.iloc[0]

id                                                                  12206946
readable                                                                True
title                           Another One Bites The Dust (Remastered 2011)
title_short                                       Another One Bites The Dust
title_version                                              (Remastered 2011)
link                                   https://www.deezer.com/track/12206946
duration                                                                 217
rank                                                                  939107
explicit_lyrics                                                        False
explicit_content_lyrics                                                    0
explicit_content_cover                                                     0
preview                    https://cdnt-preview.dzcdn.net/api/1/1/3/e/4/0...
contributors               [{'id': 412, 'name': 'Queen', 'link': 'https:/...
md5_image                                   9a20f8b2547cbb74635539c219de3a84
artist                     {'id': 412, 'name': 'Queen', 'tracklist': 'htt...
album                      {'id': 1121182, 'title': 'The Game (2011 Remas...
type                                                                   track
Name: 0, dtype: object

In [19]:
def obtener_id(diccionario):
    return diccionario["id"]


def obtener_nombre(diccionario):
    return diccionario["name"]


def obtener_titulo(diccionario):
    return diccionario["title"]

In [20]:
df_tracks_limpio = pd.DataFrame()

df_tracks_limpio["track_id"] = df_tracks["id"]
df_tracks_limpio["track_title"] = df_tracks["title"]
df_tracks_limpio["artist_id"] = df_tracks["artist"].apply(obtener_id)
df_tracks_limpio["artist_name"] = df_tracks["artist"].apply(obtener_nombre)
df_tracks_limpio["album_id"] = df_tracks["album"].apply(obtener_id)
df_tracks_limpio["album_title"] = df_tracks["album"].apply(obtener_titulo)
df_tracks_limpio["type"] = df_tracks["type"]

df_tracks_limpio.head()

,track_id,track_title,artist_id,artist_name,album_id,album_title,type
0,12206946,Another One Bites The Dust (Remastered 2011),412,Queen,1121182,The Game (2011 Remaster),track
1,9997018,Bohemian Rhapsody (Remastered 2011),412,Queen,915785,A Night At The Opera (2011 Remaster),track
2,12209331,Don't Stop Me Now (Remastered 2011),412,Queen,1121401,Jazz (2011 Remaster),track
3,12274786,Under Pressure (Remastered 2011),412,Queen,1127912,Hot Space (Deluxe Edition 2011 Remaster),track
4,7868649,Radio Ga Ga (Remastered 2011),412,Queen,726319,Greatest Hits II (2011 Remaster),track

In [21]:
df_tracks_limpio.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   track_id     5 non-null      int64
 1   track_title  5 non-null      str
 2   artist_id    5 non-null      int64
 3   artist_name  5 non-null      str
 4   album_id     5 non-null      int64
 5   album_title  5 non-null      str
 6   type         5 non-null      str
dtypes: int64(3), str(4)
memory usage: 412.0 bytes

In [22]:
params = {"limit": 50}

response_tracks = requests.get(url_top_tracks, params=params)

data_tracks = response_tracks.json()

len(data_tracks["data"])

50

In [23]:
df_tracks = pd.DataFrame(data_tracks["data"])

df_tracks_limpio = pd.DataFrame()

df_tracks_limpio["track_id"] = df_tracks["id"]
df_tracks_limpio["track_title"] = df_tracks["title"]
df_tracks_limpio["artist_id"] = df_tracks["artist"].apply(obtener_id)
df_tracks_limpio["artist_name"] = df_tracks["artist"].apply(obtener_nombre)
df_tracks_limpio["album_id"] = df_tracks["album"].apply(obtener_id)
df_tracks_limpio["album_title"] = df_tracks["album"].apply(obtener_titulo)
df_tracks_limpio["type"] = df_tracks["type"]

df_tracks_limpio.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   track_id     50 non-null     int64
 1   track_title  50 non-null     str
 2   artist_id    50 non-null     int64
 3   artist_name  50 non-null     str
 4   album_id     50 non-null     int64
 5   album_title  50 non-null     str
 6   type         50 non-null     str
dtypes: int64(3), str(4)
memory usage: 2.9 KB

In [24]:
album_id = df_tracks_limpio.iloc[0]["album_id"]

url_album = f"https://api.deezer.com/album/{album_id}"

response_album = requests.get(url_album)

data_album = response_album.json()

data_album.keys()

dict_keys(['id', 'title', 'upc', 'link', 'share', 'cover', 'cover_small', 'cover_medium', 'cover_big', 'cover_xl', 'md5_image', 'genre_id', 'genres', 'label', 'nb_tracks', 'duration', 'fans', 'release_date', 'record_type', 'available', 'tracklist', 'explicit_lyrics', 'explicit_content_lyrics', 'explicit_content_cover', 'contributors', 'artist', 'type', 'tracks'])

In [25]:
data_album

{'id': 1121182,
 'title': 'The Game (2011 Remaster)',
 'upc': '602527717517',
 'link': 'https://www.deezer.com/album/1121182',
 'share': 'https://www.deezer.com/album/1121182?utm_source=deezer&utm_content=album-1121182&utm_term=0_1779917558&utm_medium=web',
 'cover': 'https://api.deezer.com/album/1121182/image',
 'cover_small': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/56x56-000000-80-0-0.jpg',
 'cover_medium': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/250x250-000000-80-0-0.jpg',
 'cover_big': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/500x500-000000-80-0-0.jpg',
 'cover_xl': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/1000x1000-000000-80-0-0.jpg',
 'md5_image': '9a20f8b2547cbb74635539c219de3a84',
 'genre_id': 152,
 'genres': {'data': [{'id': 152,
    'name': 'Rock',
    'picture': 'https://api.deezer.com/genre/152/image',
    'type': 'genre'}]},
 'label': 'EMI',
 'nb_tracks': 10,
 'duration': 2141,
 'fans': 35179,
 'release_date': '2011-06-27',
 'record_type': 'album',
 'available': True,
 'tracklist': 'https://api.deezer.com/album/1121182/tracks',
 'explicit_lyrics': False,
 'explicit_content_lyrics': 0,
 'explicit_content_cover': 0,
 'contributors': [{'id': 412,
   'name': 'Queen',
   'link': 'https://www.deezer.com/artist/412',
   'share': 'https://www.deezer.com/artist/412?utm_source=deezer&utm_content=artist-412&utm_term=0_1779917558&utm_medium=web',
   'picture': 'https://api.deezer.com/artist/412/image',
   'picture_small': 'https://cdn-images.dzcdn.net/images/artist/71eeb9e2eeb375df35a3c0654a5a01ab/56x56-000000-80-0-0.jpg',
   'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/71eeb9e2eeb375df35a3c0654a5a01ab/250x250-000000-80-0-0.jpg',
   'picture_big': 'https://cdn-images.dzcdn.net/images/artist/71eeb9e2eeb375df35a3c0654a5a01ab/500x500-000000-80-0-0.jpg',
   'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/71eeb9e2eeb375df35a3c0654a5a01ab/1000x1000-000000-80-0-0.jpg',
   'radio': True,
   'tracklist': 'https://api.deezer.com/artist/412/top?limit=50',
   'type': 'artist',
   'role': 'Main'}],
 'artist': {'id': 412,
  'name': 'Queen',
  'picture': 'https://api.deezer.com/artist/412/image',
  'picture_small': 'https://cdn-images.dzcdn.net/images/artist/71eeb9e2eeb375df35a3c0654a5a01ab/56x56-000000-80-0-0.jpg',
  'picture_medium': 'https://cdn-images.dzcdn.net/images/artist/71eeb9e2eeb375df35a3c0654a5a01ab/250x250-000000-80-0-0.jpg',
  'picture_big': 'https://cdn-images.dzcdn.net/images/artist/71eeb9e2eeb375df35a3c0654a5a01ab/500x500-000000-80-0-0.jpg',
  'picture_xl': 'https://cdn-images.dzcdn.net/images/artist/71eeb9e2eeb375df35a3c0654a5a01ab/1000x1000-000000-80-0-0.jpg',
  'tracklist': 'https://api.deezer.com/artist/412/top?limit=50',
  'type': 'artist'},
 'type': 'album',
 'tracks': {'data': [{'id': 12206944,
    'readable': True,
    'title': 'Play The Game (Remastered 2011)',
    'title_short': 'Play The Game',
    'title_version': '(Remastered 2011)',
    'link': 'https://www.deezer.com/track/12206944',
    'duration': 213,
    'rank': 345240,
    'explicit_lyrics': False,
    'explicit_content_lyrics': 0,
    'explicit_content_cover': 0,
    'preview': 'https://cdnt-preview.dzcdn.net/api/1/1/d/9/7/0/d979abfad50a665fc93ba2ad81ec996d.mp3?hdnea=exp=1779918458~acl=/api/1/1/d/9/7/0/d979abfad50a665fc93ba2ad81ec996d.mp3*~data=user_id=0,application_id=42~hmac=3db828e6d51f24f53e139800db078628bfeac5017713dbee5fa54d236f8b9be5',
    'md5_image': '9a20f8b2547cbb74635539c219de3a84',
    'artist': {'id': 412,
     'name': 'Queen',
     'tracklist': 'https://api.deezer.com/artist/412/top?limit=50',
     'type': 'artist'},
    'album': {'id': 1121182,
     'title': 'The Game (2011 Remaster)',
     'cover': 'https://api.deezer.com/album/1121182/image',
     'cover_small': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/56x56-000000-80-0-0.jpg',
     'cover_medium': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/250x250-000000-80-0-0.jpg',
     'cover_big': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/500x500-000000-80-0-0.jpg',
     'cover_xl': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/1000x1000-000000-80-0-0.jpg',
     'md5_image': '9a20f8b2547cbb74635539c219de3a84',
     'tracklist': 'https://api.deezer.com/album/1121182/tracks',
     'type': 'album'},
    'type': 'track'},
   {'id': 12206945,
    'readable': True,
    'title': 'Dragon Attack (Remastered 2011)',
    'title_short': 'Dragon Attack',
    'title_version': '(Remastered 2011)',
    'link': 'https://www.deezer.com/track/12206945',
    'duration': 259,
    'rank': 359941,
    'explicit_lyrics': False,
    'explicit_content_lyrics': 0,
    'explicit_content_cover': 0,
    'preview': 'https://cdnt-preview.dzcdn.net/api/1/1/a/5/6/0/a5674a4e23cc054c5a0fcbbc4971bac1.mp3?hdnea=exp=1779918458~acl=/api/1/1/a/5/6/0/a5674a4e23cc054c5a0fcbbc4971bac1.mp3*~data=user_id=0,application_id=42~hmac=da04138371bdd1638b0c596d2a257cdecfaf7e65a09f5ef31b284b703a220dfa',
    'md5_image': '9a20f8b2547cbb74635539c219de3a84',
    'artist': {'id': 412,
     'name': 'Queen',
     'tracklist': 'https://api.deezer.com/artist/412/top?limit=50',
     'type': 'artist'},
    'album': {'id': 1121182,
     'title': 'The Game (2011 Remaster)',
     'cover': 'https://api.deezer.com/album/1121182/image',
     'cover_small': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/56x56-000000-80-0-0.jpg',
     'cover_medium': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/250x250-000000-80-0-0.jpg',
     'cover_big': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/500x500-000000-80-0-0.jpg',
     'cover_xl': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/1000x1000-000000-80-0-0.jpg',
     'md5_image': '9a20f8b2547cbb74635539c219de3a84',
     'tracklist': 'https://api.deezer.com/album/1121182/tracks',
     'type': 'album'},
    'type': 'track'},
   {'id': 12206946,
    'readable': True,
    'title': 'Another One Bites The Dust (Remastered 2011)',
    'title_short': 'Another One Bites The Dust',
    'title_version': '(Remastered 2011)',
    'link': 'https://www.deezer.com/track/12206946',
    'duration': 217,
    'rank': 939107,
    'explicit_lyrics': False,
    'explicit_content_lyrics': 0,
    'explicit_content_cover': 0,
    'preview': 'https://cdnt-preview.dzcdn.net/api/1/1/3/e/4/0/3e49a6a7252db65362160dfe7b379c67.mp3?hdnea=exp=1779918458~acl=/api/1/1/3/e/4/0/3e49a6a7252db65362160dfe7b379c67.mp3*~data=user_id=0,application_id=42~hmac=2a8ed50e1a2c7644e376d9433c8150ab7c91f1bbca88c04c0feefdb828c6c363',
    'md5_image': '9a20f8b2547cbb74635539c219de3a84',
    'artist': {'id': 412,
     'name': 'Queen',
     'tracklist': 'https://api.deezer.com/artist/412/top?limit=50',
     'type': 'artist'},
    'album': {'id': 1121182,
     'title': 'The Game (2011 Remaster)',
     'cover': 'https://api.deezer.com/album/1121182/image',
     'cover_small': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/56x56-000000-80-0-0.jpg',
     'cover_medium': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/250x250-000000-80-0-0.jpg',
     'cover_big': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/500x500-000000-80-0-0.jpg',
     'cover_xl': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/1000x1000-000000-80-0-0.jpg',
     'md5_image': '9a20f8b2547cbb74635539c219de3a84',
     'tracklist': 'https://api.deezer.com/album/1121182/tracks',
     'type': 'album'},
    'type': 'track'},
   {'id': 12206947,
    'readable': True,
    'title': 'Need Your Loving Tonight (Remastered 2011)',
    'title_short': 'Need Your Loving Tonight',
    'title_version': '(Remastered 2011)',
    'link': 'https://www.deezer.com/track/12206947',
    'duration': 169,
    'rank': 288877,
    'explicit_lyrics': False,
    'explicit_content_lyrics': 0,
    'explicit_content_cover': 0,
    'preview': 'https://cdnt-preview.dzcdn.net/api/1/1/6/9/3/0/69379eaed298fcf93e98ebdb6b05d4a7.mp3?hdnea=exp=1779918458~acl=/api/1/1/6/9/3/0/69379eaed298fcf93e98ebdb6b05d4a7.mp3*~data=user_id=0,application_id=42~hmac=aac42cef82bd12bc5ee01e68737361a64ab059f723a4e80e9476f397e70294b6',
    'md5_image': '9a20f8b2547cbb74635539c219de3a84',
    'artist': {'id': 412,
     'name': 'Queen',
     'tracklist': 'https://api.deezer.com/artist/412/top?limit=50',
     'type': 'artist'},
    'album': {'id': 1121182,
     'title': 'The Game (2011 Remaster)',
     'cover': 'https://api.deezer.com/album/1121182/image',
     'cover_small': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/56x56-000000-80-0-0.jpg',
     'cover_medium': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/250x250-000000-80-0-0.jpg',
     'cover_big': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/500x500-000000-80-0-0.jpg',
     'cover_xl': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/1000x1000-000000-80-0-0.jpg',
     'md5_image': '9a20f8b2547cbb74635539c219de3a84',
     'tracklist': 'https://api.deezer.com/album/1121182/tracks',
     'type': 'album'},
    'type': 'track'},
   {'id': 12206948,
    'readable': True,
    'title': 'Crazy Little Thing Called Love (Remastered 2011)',
    'title_short': 'Crazy Little Thing Called Love',
    'title_version': '(Remastered 2011)',
    'link': 'https://www.deezer.com/track/12206948',
    'duration': 164,
    'rank': 431650,
    'explicit_lyrics': False,
    'explicit_content_lyrics': 0,
    'explicit_content_cover': 0,
    'preview': 'https://cdnt-preview.dzcdn.net/api/1/1/b/0/7/0/b070cabb88c3bfd9d6baae61f803edd9.mp3?hdnea=exp=1779918458~acl=/api/1/1/b/0/7/0/b070cabb88c3bfd9d6baae61f803edd9.mp3*~data=user_id=0,application_id=42~hmac=66610210cd23295979ab14027cef3ae8ac180a0bbc3018b5fcb22e567eb24f43',
    'md5_image': '9a20f8b2547cbb74635539c219de3a84',
    'artist': {'id': 412,
     'name': 'Queen',
     'tracklist': 'https://api.deezer.com/artist/412/top?limit=50',
     'type': 'artist'},
    'album': {'id': 1121182,
     'title': 'The Game (2011 Remaster)',
     'cover': 'https://api.deezer.com/album/1121182/image',
     'cover_small': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/56x56-000000-80-0-0.jpg',
     'cover_medium': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/250x250-000000-80-0-0.jpg',
     'cover_big': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/500x500-000000-80-0-0.jpg',
     'cover_xl': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/1000x1000-000000-80-0-0.jpg',
     'md5_image': '9a20f8b2547cbb74635539c219de3a84',
     'tracklist': 'https://api.deezer.com/album/1121182/tracks',
     'type': 'album'},
    'type': 'track'},
   {'id': 12206949,
    'readable': True,
    'title': 'Rock It (Prime Jive) (Remastered 2011)',
    'title_short': 'Rock It (Prime Jive)',
    'title_version': '(Remastered 2011)',
    'link': 'https://www.deezer.com/track/12206949',
    'duration': 273,
    'rank': 275275,
    'explicit_lyrics': False,
    'explicit_content_lyrics': 0,
    'explicit_content_cover': 0,
    'preview': 'https://cdnt-preview.dzcdn.net/api/1/1/6/a/e/0/6aeaaf8ab3a2dd7cc744a3474a44fcf0.mp3?hdnea=exp=1779918458~acl=/api/1/1/6/a/e/0/6aeaaf8ab3a2dd7cc744a3474a44fcf0.mp3*~data=user_id=0,application_id=42~hmac=75163875c56bcc077c1e1a724b14f335bab074b8b3f087a3f042203e83adefef',
    'md5_image': '9a20f8b2547cbb74635539c219de3a84',
    'artist': {'id': 412,
     'name': 'Queen',
     'tracklist': 'https://api.deezer.com/artist/412/top?limit=50',
     'type': 'artist'},
    'album': {'id': 1121182,
     'title': 'The Game (2011 Remaster)',
     'cover': 'https://api.deezer.com/album/1121182/image',
     'cover_small': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/56x56-000000-80-0-0.jpg',
     'cover_medium': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/250x250-000000-80-0-0.jpg',
     'cover_big': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/500x500-000000-80-0-0.jpg',
     'cover_xl': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/1000x1000-000000-80-0-0.jpg',
     'md5_image': '9a20f8b2547cbb74635539c219de3a84',
     'tracklist': 'https://api.deezer.com/album/1121182/tracks',
     'type': 'album'},
    'type': 'track'},
   {'id': 12206950,
    'readable': True,
    'title': "Don't Try Suicide (Remastered 2011)",
    'title_short': "Don't Try Suicide",
    'title_version': '(Remastered 2011)',
    'link': 'https://www.deezer.com/track/12206950',
    'duration': 233,
    'rank': 434028,
    'explicit_lyrics': False,
    'explicit_content_lyrics': 0,
    'explicit_content_cover': 0,
    'preview': 'https://cdnt-preview.dzcdn.net/api/1/1/b/1/d/0/b1d3bb8492c997adee6aee0b72d34494.mp3?hdnea=exp=1779918458~acl=/api/1/1/b/1/d/0/b1d3bb8492c997adee6aee0b72d34494.mp3*~data=user_id=0,application_id=42~hmac=1533e9f2968354ca4c3d3e2d16a5c8698f5942a455d494c2bc3bd180f3ac1fef',
    'md5_image': '9a20f8b2547cbb74635539c219de3a84',
    'artist': {'id': 412,
     'name': 'Queen',
     'tracklist': 'https://api.deezer.com/artist/412/top?limit=50',
     'type': 'artist'},
    'album': {'id': 1121182,
     'title': 'The Game (2011 Remaster)',
     'cover': 'https://api.deezer.com/album/1121182/image',
     'cover_small': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/56x56-000000-80-0-0.jpg',
     'cover_medium': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/250x250-000000-80-0-0.jpg',
     'cover_big': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/500x500-000000-80-0-0.jpg',
     'cover_xl': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/1000x1000-000000-80-0-0.jpg',
     'md5_image': '9a20f8b2547cbb74635539c219de3a84',
     'tracklist': 'https://api.deezer.com/album/1121182/tracks',
     'type': 'album'},
    'type': 'track'},
   {'id': 12206951,
    'readable': True,
    'title': 'Sail Away Sweet Sister (Remastered 2011)',
    'title_short': 'Sail Away Sweet Sister',
    'title_version': '(Remastered 2011)',
    'link': 'https://www.deezer.com/track/12206951',
    'duration': 213,
    'rank': 295637,
    'explicit_lyrics': False,
    'explicit_content_lyrics': 0,
    'explicit_content_cover': 0,
    'preview': 'https://cdnt-preview.dzcdn.net/api/1/1/b/f/9/0/bf9159c2c7c8f417f382ae86b94967fc.mp3?hdnea=exp=1779918458~acl=/api/1/1/b/f/9/0/bf9159c2c7c8f417f382ae86b94967fc.mp3*~data=user_id=0,application_id=42~hmac=d76a81333714dfb77909a5badee2b931edb763c7fff6ccdabe0e300ab6d467e9',
    'md5_image': '9a20f8b2547cbb74635539c219de3a84',
    'artist': {'id': 412,
     'name': 'Queen',
     'tracklist': 'https://api.deezer.com/artist/412/top?limit=50',
     'type': 'artist'},
    'album': {'id': 1121182,
     'title': 'The Game (2011 Remaster)',
     'cover': 'https://api.deezer.com/album/1121182/image',
     'cover_small': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/56x56-000000-80-0-0.jpg',
     'cover_medium': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/250x250-000000-80-0-0.jpg',
     'cover_big': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/500x500-000000-80-0-0.jpg',
     'cover_xl': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/1000x1000-000000-80-0-0.jpg',
     'md5_image': '9a20f8b2547cbb74635539c219de3a84',
     'tracklist': 'https://api.deezer.com/album/1121182/tracks',
     'type': 'album'},
    'type': 'track'},
   {'id': 12206952,
    'readable': True,
    'title': 'Coming Soon (Remastered 2011)',
    'title_short': 'Coming Soon',
    'title_version': '(Remastered 2011)',
    'link': 'https://www.deezer.com/track/12206952',
    'duration': 171,
    'rank': 227976,
    'explicit_lyrics': False,
    'explicit_content_lyrics': 0,
    'explicit_content_cover': 0,
    'preview': 'https://cdnt-preview.dzcdn.net/api/1/1/b/e/3/0/be3d4a43f3d91020e7e3cfffe068d5ac.mp3?hdnea=exp=1779918458~acl=/api/1/1/b/e/3/0/be3d4a43f3d91020e7e3cfffe068d5ac.mp3*~data=user_id=0,application_id=42~hmac=c89b7600abb1cbc1bd030e028c748de00bcbc139151b382f433e0f0e5362822c',
    'md5_image': '9a20f8b2547cbb74635539c219de3a84',
    'artist': {'id': 412,
     'name': 'Queen',
     'tracklist': 'https://api.deezer.com/artist/412/top?limit=50',
     'type': 'artist'},
    'album': {'id': 1121182,
     'title': 'The Game (2011 Remaster)',
     'cover': 'https://api.deezer.com/album/1121182/image',
     'cover_small': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/56x56-000000-80-0-0.jpg',
     'cover_medium': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/250x250-000000-80-0-0.jpg',
     'cover_big': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/500x500-000000-80-0-0.jpg',
     'cover_xl': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/1000x1000-000000-80-0-0.jpg',
     'md5_image': '9a20f8b2547cbb74635539c219de3a84',
     'tracklist': 'https://api.deezer.com/album/1121182/tracks',
     'type': 'album'},
    'type': 'track'},
   {'id': 12206953,
    'readable': True,
    'title': 'Save Me (Remastered 2011)',
    'title_short': 'Save Me',
    'title_version': '(Remastered 2011)',
    'link': 'https://www.deezer.com/track/12206953',
    'duration': 229,
    'rank': 490122,
    'explicit_lyrics': False,
    'explicit_content_lyrics': 0,
    'explicit_content_cover': 0,
    'preview': 'https://cdnt-preview.dzcdn.net/api/1/1/d/0/4/0/d047cf540af78b0765abe3ba94625dff.mp3?hdnea=exp=1779918458~acl=/api/1/1/d/0/4/0/d047cf540af78b0765abe3ba94625dff.mp3*~data=user_id=0,application_id=42~hmac=380a2506aa825b578d5a406f918b89655355e32cb45d13cc34a5cd01b1648c26',
    'md5_image': '9a20f8b2547cbb74635539c219de3a84',
    'artist': {'id': 412,
     'name': 'Queen',
     'tracklist': 'https://api.deezer.com/artist/412/top?limit=50',
     'type': 'artist'},
    'album': {'id': 1121182,
     'title': 'The Game (2011 Remaster)',
     'cover': 'https://api.deezer.com/album/1121182/image',
     'cover_small': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/56x56-000000-80-0-0.jpg',
     'cover_medium': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/250x250-000000-80-0-0.jpg',
     'cover_big': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/500x500-000000-80-0-0.jpg',
     'cover_xl': 'https://cdn-images.dzcdn.net/images/cover/9a20f8b2547cbb74635539c219de3a84/1000x1000-000000-80-0-0.jpg',
     'md5_image': '9a20f8b2547cbb74635539c219de3a84',
     'tracklist': 'https://api.deezer.com/album/1121182/tracks',
     'type': 'album'},
    'type': 'track'}]}}

In [26]:
data_album["release_date"]

'2011-06-27'

In [27]:
data_album["genres"]

{'data': [{'id': 152,
   'name': 'Rock',
   'picture': 'https://api.deezer.com/genre/152/image',
   'type': 'genre'}]}

In [28]:
def obtener_anio(fecha):
    return fecha[:4]


def obtener_genero_id(generos):
    return generos["data"][0]["id"]


def obtener_genero_nombre(generos):
    return generos["data"][0]["name"]

In [29]:
release_date = data_album["release_date"]

anio = obtener_anio(release_date)

genre_id = obtener_genero_id(data_album["genres"])

genre_name = obtener_genero_nombre(data_album["genres"])

print(anio)
print(genre_id)
print(genre_name)

2011
152
Rock

In [30]:
anios = []
genres_ids = []
genres_names = []

In [31]:
for album_id in df_tracks_limpio["album_id"]:

    url_album = f"https://api.deezer.com/album/{album_id}"

    response_album = requests.get(url_album)

    data_album = response_album.json()

    # Año
    release_date = data_album["release_date"]
    anio = obtener_anio(release_date)

    # Género
    genre_id = obtener_genero_id(data_album["genres"])
    genre_name = obtener_genero_nombre(data_album["genres"])

    # Guardar en listas
    anios.append(anio)
    genres_ids.append(genre_id)
    genres_names.append(genre_name)

    # pequeña pausa para no saturar la API
    time.sleep(0.2)

In [32]:
df_tracks_limpio["release_year"] = anios
df_tracks_limpio["genre_id"] = genres_ids
df_tracks_limpio["genre_name"] = genres_names

In [33]:
df_tracks_limpio.head()

,track_id,track_title,artist_id,artist_name,album_id,album_title,type,release_year,genre_id,genre_name
0,12206946,Another One Bites The Dust (Remastered 2011),412,Queen,1121182,The Game (2011 Remaster),track,2011,152,Rock
1,9997018,Bohemian Rhapsody (Remastered 2011),412,Queen,915785,A Night At The Opera (2011 Remaster),track,2005,152,Rock
2,12209331,Don't Stop Me Now (Remastered 2011),412,Queen,1121401,Jazz (2011 Remaster),track,2011,152,Rock
3,12274786,Under Pressure (Remastered 2011),412,Queen,1127912,Hot Space (Deluxe Edition 2011 Remaster),track,2011,152,Rock
4,7868649,Radio Ga Ga (Remastered 2011),412,Queen,726319,Greatest Hits II (2011 Remaster),track,2011,152,Rock

In [34]:
album_ids_unicos = df_tracks_limpio["album_id"].unique()

len(album_ids_unicos)

20

In [35]:
def obtener_info_album(album_id):
    url_album = f"https://api.deezer.com/album/{album_id}"
    response_album = requests.get(url_album)

    if response_album.status_code != 200:
        return {
            "album_id": album_id,
            "release_year": None,
            "genre_id": None,
            "genre_name": None
        }

    data_album = response_album.json()

    release_date = data_album.get("release_date")

    if release_date:
        release_year = release_date[:4]
    else:
        release_year = None

    genres = data_album.get("genres", {}).get("data", [])

    if genres:
        genre_id = genres[0].get("id")
        genre_name = genres[0].get("name")
    else:
        genre_id = None
        genre_name = None

    return {
        "album_id": album_id,
        "release_year": release_year,
        "genre_id": genre_id,
        "genre_name": genre_name
    }

In [36]:
albumes_info = []

for album_id in album_ids_unicos:

    info_album = obtener_info_album(album_id)

    albumes_info.append(info_album)

    time.sleep(0.2)

In [37]:
df_albums = pd.DataFrame(albumes_info)

In [38]:
df_albums.head()

   album_id release_year  genre_id genre_name
0   1121182         2011       152       Rock
1    915785         2005       152       Rock
2   1121401         2011       152       Rock
3   1127912         2011       152       Rock
4    726319         2011       152       Rock

In [43]:
df_tracks_limpio = df_tracks_limpio.drop(
    columns=["release_year", "genre_id", "genre_name"],
    errors="ignore")

In [44]:
df_tracks_final = df_tracks_limpio.merge(
    df_albums,
    on="album_id",
    how="left"
)

In [46]:
df_tracks_final.head()

,track_id,track_title,artist_id,artist_name,album_id,album_title,type,release_year,genre_id,genre_name
0,12206946,Another One Bites The Dust (Remastered 2011),412,Queen,1121182,The Game (2011 Remaster),track,2011,152,Rock
1,9997018,Bohemian Rhapsody (Remastered 2011),412,Queen,915785,A Night At The Opera (2011 Remaster),track,2005,152,Rock
2,12209331,Don't Stop Me Now (Remastered 2011),412,Queen,1121401,Jazz (2011 Remaster),track,2011,152,Rock
3,12274786,Under Pressure (Remastered 2011),412,Queen,1127912,Hot Space (Deluxe Edition 2011 Remaster),track,2011,152,Rock
4,7868649,Radio Ga Ga (Remastered 2011),412,Queen,726319,Greatest Hits II (2011 Remaster),track,2011,152,Rock

In [47]:
df_tracks_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   track_id      50 non-null     int64
 1   track_title   50 non-null     str
 2   artist_id     50 non-null     int64
 3   artist_name   50 non-null     str
 4   album_id      50 non-null     int64
 5   album_title   50 non-null     str
 6   type          50 non-null     str
 7   release_year  50 non-null     str
 8   genre_id      50 non-null     int64
 9   genre_name    50 non-null     str
dtypes: int64(4), str(6)
memory usage: 4.0 KB

In [68]:
def obtener_tracks_artista(nombre_artista):
    # 1. Buscar artista
    url_artist = "https://api.deezer.com/search/artist"
    params_artist = {"q": nombre_artista}

    response_artist = requests.get(url_artist, params=params_artist)
    data_artist = response_artist.json()

    if not data_artist["data"]:
        print(f"No se encontró artista: {nombre_artista}")
        return pd.DataFrame()

    artist_id = data_artist["data"][0]["id"]
    artist_name = data_artist["data"][0]["name"]

    # 2. Obtener top 50 canciones
    url_tracks = f"https://api.deezer.com/artist/{artist_id}/top"
    params_tracks = {"limit": 50}

    response_tracks = requests.get(url_tracks, params=params_tracks)
    data_tracks = response_tracks.json()

    df_tracks = pd.DataFrame(data_tracks["data"])

    if df_tracks.empty:
        print(f"No se encontraron canciones para: {artist_name}")
        return pd.DataFrame()

    # 3. Limpiar canciones
    df_tracks_limpio = pd.DataFrame()

    df_tracks_limpio["track_id"] = df_tracks["id"]
    df_tracks_limpio["track_title"] = df_tracks["title"]
    df_tracks_limpio["artist_id"] = artist_id
    df_tracks_limpio["artist_name"] = artist_name
    df_tracks_limpio["album_id"] = df_tracks["album"].apply(obtener_id)
    df_tracks_limpio["album_title"] = df_tracks["album"].apply(obtener_titulo)
    df_tracks_limpio["type"] = df_tracks["type"]

    # 4. Consultar solo álbumes únicos
    album_ids_unicos = df_tracks_limpio["album_id"].unique()

    albumes_info = []

    for album_id in album_ids_unicos:
        info_album = obtener_info_album(album_id)
        albumes_info.append(info_album)
        time.sleep(0.2)

    df_albums = pd.DataFrame(albumes_info)

    # 5. Unir canciones con info de álbum
    df_tracks_final = df_tracks_limpio.merge(
    df_albums,
    on="album_id",
    how="left")

    # convertir año a entero
    df_tracks_final["release_year"] = (
    df_tracks_final["release_year"].astype(int))

    return df_tracks_final

In [58]:
df_queen = obtener_tracks_artista("Queen")

df_queen.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   track_id      50 non-null     int64
 1   track_title   50 non-null     str
 2   artist_id     50 non-null     int64
 3   artist_name   50 non-null     str
 4   album_id      50 non-null     int64
 5   album_title   50 non-null     str
 6   type          50 non-null     str
 7   release_year  50 non-null     int64
 8   genre_id      50 non-null     int64
 9   genre_name    50 non-null     str
dtypes: int64(5), str(5)
memory usage: 4.0 KB

In [59]:
df_queen.head()

,track_id,track_title,artist_id,artist_name,album_id,album_title,type,release_year,genre_id,genre_name
0,12206946,Another One Bites The Dust (Remastered 2011),412,Queen,1121182,The Game (2011 Remaster),track,2011,152,Rock
1,9997018,Bohemian Rhapsody (Remastered 2011),412,Queen,915785,A Night At The Opera (2011 Remaster),track,2005,152,Rock
2,12209331,Don't Stop Me Now (Remastered 2011),412,Queen,1121401,Jazz (2011 Remaster),track,2011,152,Rock
3,12274786,Under Pressure (Remastered 2011),412,Queen,1127912,Hot Space (Deluxe Edition 2011 Remaster),track,2011,152,Rock
4,7868649,Radio Ga Ga (Remastered 2011),412,Queen,726319,Greatest Hits II (2011 Remaster),track,2011,152,Rock

In [60]:
artistas_70_80 = [
    "Queen",
    "ABBA",
    "Fleetwood Mac",
    "David Bowie",
    "Elton John",
    "Bee Gees",
    "Pink Floyd",
    "The Rolling Stones",
    "Led Zeppelin",
    "AC/DC",
    "The Police",
    "Dire Straits",
    "Blondie",
    "The Clash",
    "Ramones",
    "Talking Heads",
    "Michael Jackson",
    "Madonna",
    "Prince",
    "Whitney Houston",
    "Bon Jovi",
    "U2",
    "Metallica",
    "Guns N' Roses",
    "Depeche Mode",
    "The Cure",
    "Duran Duran",
    "Eurythmics",
    "a-ha",
    "George Michael"
]

In [61]:
artistas_test = [
    "Queen",
    "ABBA",
    "Madonna"
]

In [62]:
dfs_artistas = []

In [63]:
for artista in artistas_test:

    print(f"Extrayendo datos de: {artista}")

    df_artista = obtener_tracks_artista(artista)

    dfs_artistas.append(df_artista)

    print(f"{artista}: {len(df_artista)} canciones")

Extrayendo datos de: Queen
Queen: 50 canciones
Extrayendo datos de: ABBA
ABBA: 50 canciones
Extrayendo datos de: Madonna
Madonna: 50 canciones

In [64]:
df_final = pd.concat(dfs_artistas, ignore_index=True)

In [65]:
df_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   track_id      150 non-null    int64
 1   track_title   150 non-null    str
 2   artist_id     150 non-null    int64
 3   artist_name   150 non-null    str
 4   album_id      150 non-null    int64
 5   album_title   150 non-null    str
 6   type          150 non-null    str
 7   release_year  150 non-null    int64
 8   genre_id      150 non-null    int64
 9   genre_name    150 non-null    str
dtypes: int64(5), str(5)
memory usage: 11.8 KB

In [66]:
df_final.head()

,track_id,track_title,artist_id,artist_name,album_id,album_title,type,release_year,genre_id,genre_name
0,12206946,Another One Bites The Dust (Remastered 2011),412,Queen,1121182,The Game (2011 Remaster),track,2011,152,Rock
1,9997018,Bohemian Rhapsody (Remastered 2011),412,Queen,915785,A Night At The Opera (2011 Remaster),track,2005,152,Rock
2,12209331,Don't Stop Me Now (Remastered 2011),412,Queen,1121401,Jazz (2011 Remaster),track,2011,152,Rock
3,12274786,Under Pressure (Remastered 2011),412,Queen,1127912,Hot Space (Deluxe Edition 2011 Remaster),track,2011,152,Rock
4,7868649,Radio Ga Ga (Remastered 2011),412,Queen,726319,Greatest Hits II (2011 Remaster),track,2011,152,Rock

In [67]:
df_final["artist_name"].value_counts()

artist_name
ABBA              50
Queen             49
Madonna           48
George Michael     1
The Weeknd         1
Beyoncé            1
Name: count, dtype: int64

In [69]:
dfs_artistas = []

for artista in artistas_test:
    print(f"Extrayendo datos de: {artista}")
    df_artista = obtener_tracks_artista(artista)
    dfs_artistas.append(df_artista)
    print(f"{artista}: {len(df_artista)} canciones")

df_final = pd.concat(dfs_artistas, ignore_index=True)

df_final["artist_name"].value_counts()

Extrayendo datos de: Queen
Queen: 50 canciones
Extrayendo datos de: ABBA
ABBA: 50 canciones
Extrayendo datos de: Madonna
Madonna: 50 canciones

artist_name
Queen      50
ABBA       50
Madonna    50
Name: count, dtype: int64

In [70]:
dfs_artistas = []

for artista in artistas_70_80:
    print(f"Extrayendo datos de: {artista}")

    df_artista = obtener_tracks_artista(artista)

    dfs_artistas.append(df_artista)

    print(f"{artista}: {len(df_artista)} canciones")

df_final = pd.concat(dfs_artistas, ignore_index=True)

Extrayendo datos de: Queen
Queen: 50 canciones
Extrayendo datos de: ABBA
ABBA: 50 canciones
Extrayendo datos de: Fleetwood Mac
Fleetwood Mac: 50 canciones
Extrayendo datos de: David Bowie
David Bowie: 50 canciones
Extrayendo datos de: Elton John
Elton John: 50 canciones
Extrayendo datos de: Bee Gees
Bee Gees: 50 canciones
Extrayendo datos de: Pink Floyd
Pink Floyd: 50 canciones
Extrayendo datos de: The Rolling Stones
The Rolling Stones: 50 canciones
Extrayendo datos de: Led Zeppelin
Led Zeppelin: 50 canciones
Extrayendo datos de: AC/DC
AC/DC: 50 canciones
Extrayendo datos de: The Police
The Police: 50 canciones
Extrayendo datos de: Dire Straits
Dire Straits: 50 canciones
Extrayendo datos de: Blondie
Blondie: 50 canciones
Extrayendo datos de: The Clash
The Clash: 50 canciones
Extrayendo datos de: Ramones
Ramones: 50 canciones
Extrayendo datos de: Talking Heads
Talking Heads: 50 canciones
Extrayendo datos de: Michael Jackson
Michael Jackson: 50 canciones
Extrayendo datos de: Madonna
Madonna: 50 canciones
Extrayendo datos de: Prince
Prince: 50 canciones
Extrayendo datos de: Whitney Houston
Whitney Houston: 50 canciones
Extrayendo datos de: Bon Jovi
Bon Jovi: 50 canciones
Extrayendo datos de: U2
U2: 50 canciones
Extrayendo datos de: Metallica
Metallica: 50 canciones
Extrayendo datos de: Guns N' Roses
Guns N' Roses: 50 canciones
Extrayendo datos de: Depeche Mode
Depeche Mode: 50 canciones
Extrayendo datos de: The Cure
The Cure: 50 canciones
Extrayendo datos de: Duran Duran
Duran Duran: 50 canciones
Extrayendo datos de: Eurythmics
Eurythmics: 50 canciones
Extrayendo datos de: a-ha
a-ha: 50 canciones
Extrayendo datos de: George Michael
George Michael: 50 canciones

In [71]:
df_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   track_id      1500 non-null   int64
 1   track_title   1500 non-null   str
 2   artist_id     1500 non-null   int64
 3   artist_name   1500 non-null   str
 4   album_id      1500 non-null   int64
 5   album_title   1500 non-null   str
 6   type          1500 non-null   str
 7   release_year  1500 non-null   int64
 8   genre_id      1500 non-null   int64
 9   genre_name    1500 non-null   str
dtypes: int64(5), str(5)
memory usage: 117.3 KB

In [72]:
df_final["artist_name"].value_counts()

artist_name
Queen                 50
ABBA                  50
Fleetwood Mac         50
David Bowie           50
Elton John            50
Bee Gees              50
Pink Floyd            50
The Rolling Stones    50
Led Zeppelin          50
AC/DC                 50
The Police            50
Dire Straits          50
Blondie               50
The Clash             50
Ramones               50
Talking Heads         50
Michael Jackson       50
Madonna               50
Prince                50
Whitney Houston       50
Bon Jovi              50
U2                    50
Metallica             50
Guns N' Roses         50
Depeche Mode          50
The Cure              50
Duran Duran           50
Eurythmics            50
a-ha                  50
George Michael        50
Name: count, dtype: int64

In [73]:
df_artists_sql = df_final[
    ["artist_id", "artist_name"]
].drop_duplicates()

In [74]:
df_artists_sql.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 1450
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   artist_id    30 non-null     int64
 1   artist_name  30 non-null     str
dtypes: int64(1), str(1)
memory usage: 612.0 bytes

In [75]:
df_artists_sql.head()

     artist_id    artist_name
0          412          Queen
50         180           ABBA
100        169  Fleetwood Mac
150        997    David Bowie
200        413     Elton John

In [76]:
df_genres_sql = df_final[
    ["genre_id", "genre_name"]
].drop_duplicates()

In [77]:
df_albums_sql = df_final[
    [
        "album_id",
        "album_title",
        "release_year",
        "genre_id"
    ]
].drop_duplicates()

In [78]:
df_tracks_sql = df_final[
    [
        "track_id",
        "track_title",
        "artist_id",
        "album_id",
        "type"
    ]
].drop_duplicates()