In [2]:
import requests
import pandas as pd

In [3]:
import mysql.connector
from mysql.connector import Error
import numpy as np

In [3]:
import os

In [4]:
import requests
import pandas as pd

def conseguir_canciones(artist_name, limit=50):     # Función para conseguir 50 canciones de la artista que quieras
    url = "https://api.deezer.com/search"           # URL base de la API para buscar
    params = {                                      # Para insertar los parámetros de la búsqueda
        "q": f'artist:"{artist_name}"',             # La API busca artista por q
        "limit": limit                              # Limit sirve para que saque solo 50
    }
    try:                                            # Bloque try/excep para llamar a la API y que nos dé el resultado
        response = requests.get(url, params=params)
        if response.status_code != 200:
            print("Error en la llamada a Deezer:", response.status_code)    # Si falla lo va a informar
            return pd.DataFrame([])                                         # Y también nos va a devolver el DF vacío
        data = response.json()                                              # Si no falla da la respuesta en json
    except Error as e:
        print("Error en la llamada a Deezer:", e)                           # Para que nos diga exactamente cuál es el error
        return pd.DataFrame([])

    canciones = data.get("data", [])                # Obtiene la lista de canciones
    lista_canciones = []                            # Lista donde se van a acumular las filas para el DF final

    for cancion in canciones:                       # Bucle para que itere con todas las canciones y nos vaya dando los datos
        track_id = cancion["id"]                    # Nos da el id de la canción
        track = requests.get(f"https://api.deezer.com/track/{track_id}").json()  # Pide todos los datos que estén en track
        album = requests.get(f"https://api.deezer.com/album/{track['album']['id']}").json() # Pide todos los datos que estén en album

        genre_id = album.get("genre_id")   # Extrae el ID del género de album
        genre_name = None                  # Creamos la variable "vacía"
        if album.get("genres") and album["genres"].get("data"):   # Le decimoa que en el caso de que genres exista en album
            genre_name = album["genres"]["data"][0].get("name")   # Entonces nos diga el primer género que aparezca (por si hay varios)

        tracks_type = "colaboracion" if len(track.get("contributors", [])) > 1 else album.get("record_type", "track")
        # Buscamos colaboraciones. Para ello, si en contributor aparece más de 1, entonces se trata de una colaboración
        # Si no, le decimos que nos ponga lo que aparezca en record_type que es single o album, y si no que ponga track
        release_year = track.get("release_date", "")[:4] if track.get("release_date") else None
        # Obtiene el año de lanzamiento solo si hay 4 cifras, si no pondrá None 
        lista_canciones.append({                   # Creamos un diccionario para añadir todos los datos que necesitamos
            "id_artista": track["artist"]["id"],
            "nombre_artista": artist_name,
            "titulo_cancion": track["title"],
            "titulo_album": track["album"]["title"],
            "tipo": tracks_type,
            "año_lanzamiento": release_year,
            "genero": genre_name,
            "id_genero": genre_id,
        })

    return pd.DataFrame(lista_canciones)        # Hacemos que nos devuelta el resultado en un DF

df_artista = conseguir_canciones("Janis Joplin", limit=50)
df_artista

,id_artista,nombre_artista,titulo_cancion,titulo_album,tipo,año_lanzamiento,genero,id_genero
0,13840,Janis Joplin,Piece of My Heart,The Essential Janis Joplin,colaboracion,2003,Rock,152
1,1658,Janis Joplin,Me and Bobby McGee,Pearl (Legacy Edition),album,1971,Rock,152
2,1658,Janis Joplin,Cry Baby,Pearl (Legacy Edition),album,1971,Rock,152
3,1658,Janis Joplin,Kozmic Blues,I Got Dem Ol' Kozmic Blues Again Mama!,album,1969,Rock,152
4,13840,Janis Joplin,Call On Me,Box Of Pearls,colaboracion,1999,Rock,152
5,13840,Janis Joplin,Summertime,The Essential Janis Joplin,colaboracion,2003,Rock,152
6,1658,Janis Joplin,Little Girl Blue,I Got Dem Ol' Kozmic Blues Again Mama!,album,1969,Rock,152
7,1658,Janis Joplin,Move Over,Pearl,album,1971,Pop,132
8,13840,Janis Joplin,Ball and Chain,Iconic Performances from the Monterey Internat...,colaboracion,2017,Rock,152
9,1658,Janis Joplin,Maybe,Janis: Little Girl Blue (Original Motion Pictu...,album,2016,Rock,152
10,1658,Janis Joplin,Cry Baby (Alternate Version),The Pearl Sessions,album,1971,Rock,152
11,1658,Janis Joplin,Piece Of My Heart (Live at The Woodstock Music...,Janis Joplin: The Woodstock Experience,album,2009,Rock,152
12,1658,Janis Joplin,To Love Somebody,I Got Dem Ol' Kozmic Blues Again Mama!,album,1969,Rock,152
13,13840,Janis Joplin,"Bye, Bye Baby",Janis Joplin's Greatest Hits,colaboracion,1973,Pop,132
14,1658,Janis Joplin,Mercedes Benz,Pearl (Legacy Edition),album,1971,Rock,152
15,1658,Janis Joplin,Get It While You Can,Pearl (Legacy Edition),album,1971,Rock,152
16,1658,Janis Joplin,Try (Just a Little Bit Harder),I Got Dem Ol' Kozmic Blues Again Mama!,album,1969,Rock,152
17,1658,Janis Joplin,Little Girl Blue,Janis: Little Girl Blue (Original Motion Pictu...,album,2016,Rock,152
18,13840,Janis Joplin,Coo Coo (Single Version),The Essential Janis Joplin,colaboracion,2003,Rock,152
19,13840,Janis Joplin,Turtle Blues (Take 9),"Sex, Dope & Cheap Thrills",colaboracion,2018,Rock,152
20,13840,Janis Joplin,"Down On Me (Live at The Grande Ballroom, Detro...",Janis Joplin's Greatest Hits,colaboracion,1973,Pop,132
21,1658,Janis Joplin,"Kozmic Blues (Live at CNE Stadium, Toronto, Ca...",Pearl (Legacy Edition),album,1971,Rock,152
22,1658,Janis Joplin,"Move Over (Live at McMahon Stadium, Calgary, C...",Pearl (Legacy Edition),album,1971,Rock,152
23,1658,Janis Joplin,Summertime (Live at The Woodstock Music & Art ...,Janis Joplin: The Woodstock Experience,album,2009,Rock,152
24,1658,Janis Joplin,Half Moon,Pearl,album,1971,Pop,132
25,13840,Janis Joplin,Piece of My Heart (Live at The Grande Ballroom...,Joplin In Concert,colaboracion,1972,Rock,152
26,1658,Janis Joplin,Take Another Piece of my Heart (Live SWR TV Fr...,The Television Broadcast Sessions 1968 -1970,album,2017,Rock,152
27,1658,Janis Joplin,Pearl (Instrumental),Pearl (Legacy Edition),album,1971,Rock,152
28,13840,Janis Joplin,Ball and Chain,Box Of Pearls,colaboracion,1999,Rock,152
29,1658,Janis Joplin,My Baby (Alternate Version),Pearl (Legacy Edition),album,1971,Rock,152
30,13840,Janis Joplin,Blindman,Big Brother & The Holding Company,colaboracion,1967,Rock,152
31,455579,Janis Joplin,One Night Stand,Farewell Song,colaboracion,1981,Rock,152
32,69919,Janis Joplin,"Oh, Sweet Mary",Cheap Thrills,album,1968,Rock,152
33,1658,Janis Joplin,One Good Man,I Got Dem Ol' Kozmic Blues Again Mama!,album,1969,Rock,152
34,1658,Janis Joplin,"Cry Baby (Live at McMahon Stadium, Calgary, Ca...",Janis: Little Girl Blue (Original Motion Pictu...,album,2016,Rock,152
35,1658,Janis Joplin,A Woman Left Lonely,Pearl,album,1971,Pop,132
36,13840,Janis Joplin,Summertime (From 'Porgy & Bess') (Live at the ...,Janis Joplin Live At Winterland '68,colaboracion,1998,Rock,152
37,1658,Janis Joplin,My Baby,Pearl (Legacy Edition),album,1971,Rock,152
38,1658,Janis Joplin,Move Over (Alternate Version),Pearl (Legacy Edition),album,1971,Rock,152
39,1658,Janis Joplin,Me And Bobby McGee (Mono Single),The Pearl Sessions,album,1971,Rock,152
40,13840,Janis Joplin,I Need a Man to Love (Live at the Winterland B...,Janis Joplin Live At Winterland '68,colaboracion,1998,Rock,152
41,13840,Janis Joplin,"Bye, Bye Baby",Big Brother & The Holding Company,colaboracion,2026,Rock,152
42,1658,Janis Joplin,"Work Me, Lord",I Got Dem Ol' Kozmic Blues Again Mama!,album,1969,Rock,152
43,69919,Janis Joplin,Roadblock,Cheap Thrills,album,1968,Rock,152
44,69919,Janis Joplin,Turtle Blues,Cheap Thrills,album,1968,Rock,152
45,1658,Janis Joplin,"Half Moon (Live at CNE Stadium, Toronto, Canad...",Pearl (Legacy Edition),album,1971,Rock,152
46,69919,Janis Joplin,Flower In the Sun,Cheap Thrills,album,1968,Rock,152
47,13840,Janis Joplin,Women Is Losers,The Essential Janis Joplin,colaboracion,2003,Rock,152
48,1658,Janis Joplin,Ball and Chain (Live 1969),One From The Heart (Live 1969),album,2019,Rock,152
49,1658,Janis Joplin,"Ball and Chain (Live at McMahon Stadium, Calga...",Janis Joplin's Greatest Hits,album,1973,Pop,132

In [5]:
df_artista.to_csv("janis.csv", index=False)

In [4]:
def conseguir_canciones(artist_name, limit=50):     # Función para conseguir 50 canciones de la artista que quieras
    url = "https://api.deezer.com/search"           # URL base de la API para buscar
    params = {                                      # Para insertar los parámetros de la búsqueda
        "q": f'artist:"{artist_name}"',             # La API busca artista por q
        "limit": limit                              # Limit sirve para que saque solo 50
    }
    try:                                            # Bloque try/excep para llamar a la API y que nos dé el resultado
        response = requests.get(url, params=params)
        if response.status_code != 200:
            print("Error en la llamada a Deezer:", response.status_code)    # Si falla lo va a informar
            return pd.DataFrame([])                                         # Y también nos va a devolver el DF vacío
        data = response.json()                                              # Si no falla da la respuesta en json
    except Error as e:
        print("Error en la llamada a Deezer:", e)                           # Para que nos diga exactamente cuál es el error
        return pd.DataFrame([])

    canciones = data.get("data", [])                # Obtiene la lista de canciones
    lista_canciones = []                            # Lista donde se van a acumular las filas para el DF final

    for cancion in canciones:                       # Bucle para que itere con todas las canciones y nos vaya dando los datos
        track_id = cancion["id"]                    # Nos da el id de la canción
        track = requests.get(f"https://api.deezer.com/track/{track_id}").json()  # Pide todos los datos que estén en track
        album = requests.get(f"https://api.deezer.com/album/{track['album']['id']}").json() # Pide todos los datos que estén en album

        genre_id = album.get("genre_id")   # Extrae el ID del género de album
        genre_name = None                  # Creamos la variable "vacía"
        if album.get("genres") and album["genres"].get("data"):   # Le decimoa que en el caso de que genres exista en album
            genre_name = album["genres"]["data"][0].get("name")   # Entonces nos diga el primer género que aparezca (por si hay varios)

        tracks_type = "colaboracion" if len(track.get("contributors", [])) > 1 else album.get("record_type", "track")
        # Buscamos colaboraciones. Para ello, si en contributor aparece más de 1, entonces se trata de una colaboración
        # Si no, le decimos que nos ponga lo que aparezca en record_type que es single o album, y si no que ponga track
        release_year = track.get("release_date", "")[:4] if track.get("release_date") else None
        # Obtiene el año de lanzamiento solo si hay 4 cifras, si no pondrá None 
        lista_canciones.append({                   # Creamos un diccionario para añadir todos los datos que necesitamos
            "id_artista": track["artist"]["id"],
            "nombre_artista": artist_name,
            "titulo_cancion": track["title"],
            "titulo_album": track["album"]["title"],
            "tipo": tracks_type,
            "año_lanzamiento": release_year,
            "genero": genre_name,
            "id_genero": genre_id,
        })

    return pd.DataFrame(lista_canciones)        # Hacemos que nos devuelta el resultado en un DF

df_artista = conseguir_canciones("Celia Cruz", limit=50)
df_artista

,id_artista,nombre_artista,titulo_cancion,titulo_album,tipo,año_lanzamiento,genero,id_genero
0,5024,Celia Cruz,La Vida Es Un Carnaval,La Vida Es Un Carnaval (Baile Total),album,2017,Latino,197
1,5024,Celia Cruz,La Dicha Mía (Remastered 2026),"Celia, Johnny and Pete (Remastered 2026)",colaboracion,2026,Latino,197
2,5024,Celia Cruz,Oye Cómo Va,"Fania Records: The 60's, Vol. Three",colaboracion,2019,Latino,197
3,2789,Celia Cruz,El Ultimo Adiós Varios Artistas Version,El Ultimo Adiós,colaboracion,2001,Pop,132
4,5024,Celia Cruz,La Negra Tiene Tumbao,La Reina Y Sus Amigos,album,2009,Latino,197
5,84998,Celia Cruz,Quimbara,"Salsa Party, Vol. 2",colaboracion,2019,Latino,197
6,5024,Celia Cruz,Yo Viviré (I Will Survive),Siempre Viviré,album,2000,Salsa,67
7,84998,Celia Cruz,Canto A La Habana,Fania Classics: Celia Cruz & Johnny Pacheco,colaboracion,2019,Latino,197
8,5678,Celia Cruz,A lo loco (con Celia Cruz),Grandes Exitos?,colaboracion,2003,Latino,197
9,5024,Celia Cruz,Rie y Llora,Soy Mujer,album,2014,Latino,197
10,5024,Celia Cruz,Te Busco,Para La Eternidad,album,2016,Latino,197
11,4106065,Celia Cruz,"Quizas, Quizas, Quizas - Original",Salsa Queen CD3,compile,2006,Electro,106
12,5024,Celia Cruz,Usted Abusó,Celia,colaboracion,2019,Latino,197
13,2395,Celia Cruz,"Guantanamera (feat. Ms. Lauryn Hill, Celia Cru...",Wyclef Jean presents The Carnival featuring Re...,colaboracion,1997,Pop,132
14,5024,Celia Cruz,Mi Bomba Sono,Salsa Queen,album,2003,Latino,197
15,1084754,Celia Cruz,Azúcar (feat. Arturo Sandoval),ASUCCAR,colaboracion,2026,Salsa,67
16,5024,Celia Cruz,Todos Somos Iguales (Remastered 2024),Only They Could Have Made This Album (Remaster...,colaboracion,2024,Latino,197
17,5024,Celia Cruz,La Vida Es Un Carnaval,Salsa,album,2007,Pop,132
18,5024,Celia Cruz,Tu Voz,Boleros,album,2019,Latino,197
19,5024,Celia Cruz,Yerberito Moderno,Tu Voz,album,2022,Latino,197
20,5024,Celia Cruz,Guantanamera,50 éxitos de salsa cubana,album,2015,Salsa,67
21,5024,Celia Cruz,Quimbara (Live),Lo Mejor De Celia Cruz & Oscar D´León En Conci...,album,2014,Latino,197
22,5130,Celia Cruz,El Chisme,Ritmo en el Corazón,colaboracion,2019,Latino,197
23,5024,Celia Cruz,La Vida Es Un Carnaval (4F Remix),La Vida Es Un Carnaval (4F Remix),colaboracion,2018,Pop,132
24,5024,Celia Cruz,Contestación de el Marinero (Merengue),La Reina de la Salsa (Con la Sonora Matancera),album,2011,Salsa,67
25,5024,Celia Cruz,Y Mi Negro Esta' Cansado,Latin Legends,compile,2015,Latino,197
26,5024,Celia Cruz,Rock And Roll,Mango Mangue,album,2007,NaN,-1
27,93479,Celia Cruz,La Guagua - Original,Cuban Legend,compile,2011,NaN,-1
28,5024,Celia Cruz,"Mi Amor, Buenas Noches",Poco Poco,album,2015,NaN,-1
29,5024,Celia Cruz,"Goza Negra, Guaracha",Vintage Music No. 131 - LP: Celia Cruz,colaboracion,2010,Salsa,67
30,5024,Celia Cruz,Ven bernabe,Con Amor,colaboracion,2014,NaN,-1
31,5024,Celia Cruz,Cachunga,La Mania De Mamaita,album,2014,Salsa,67
32,5024,Celia Cruz,Guantanamera,Celia,album,2019,Latino,197
33,5024,Celia Cruz,El Tumbao Y Celia,Fania Classics: Celia Cruz & Johnny Pacheco,colaboracion,2019,Latino,197
34,5024,Celia Cruz,Quimbara,Havana Nights,album,2019,Salsa,67
35,5024,Celia Cruz,Dos Días En La Vida,Siempre Viviré,album,2000,Salsa,67
36,5024,Celia Cruz,Bemba Colorá,Viva la Reina de la Salsa,album,2019,Latino,197
37,84998,Celia Cruz,Toro Mata,The 'Brillante' Best,colaboracion,2019,Latino,197
38,5002,Celia Cruz,Tres Gotas De Agua Bendita (feat. Celia Cruz) ...,Tres Gotas De Agua Bendita,colaboracion,2000,Pop,132
39,279489,Celia Cruz,Celia,Celia,colaboracion,2024,Latino,197
40,84998,Celia Cruz,No Mercedes,Fania Classics: Celia Cruz & Johnny Pacheco,colaboracion,2019,Latino,197
41,55870,Celia Cruz,Bamboléo,Greatest Hits,colaboracion,2019,Latino,197
42,5024,Celia Cruz,Dile Que Por Mí No Tema,A Lady And Her Music: ¡Azucar!,colaboracion,2019,Latino,197
43,5024,Celia Cruz,Celia's Oye Como Va (Oye Como Va),Siempre Viviré,album,2000,Latino,197
44,191162,Celia Cruz,Burundanga,Canta Celia Cruz,colaboracion,2019,Latino,197
45,5024,Celia Cruz,Tres Días De Carnaval,Fania Classics: Celia Cruz & Johnny Pacheco,colaboracion,2019,Latino,197
46,5024,Celia Cruz,A Papá,Only They Could Have Made This Album,colaboracion,2019,Latino,197
47,191162,Celia Cruz,Pa La Paloma,Cuba's Queen Of Rhythm,colaboracion,2019,Latino,197
48,5024,Celia Cruz,Dile Que por Mí No Tema,"Antología Romántica: Grandes Voces, Grandes Bo...",colaboracion,2014,Latino,197
49,5024,Celia Cruz,"Quizás, quizás, quizás",50 éxitos de salsa cubana,album,2015,Salsa,67

In [5]:
df_artista.to_csv("celia.csv", index=False)

In [6]:
def conseguir_canciones(artist_name, limit=50):     # Función para conseguir 50 canciones de la artista que quieras
    url = "https://api.deezer.com/search"           # URL base de la API para buscar
    params = {                                      # Para insertar los parámetros de la búsqueda
        "q": f'artist:"{artist_name}"',             # La API busca artista por q
        "limit": limit                              # Limit sirve para que saque solo 50
    }
    try:                                            # Bloque try/excep para llamar a la API y que nos dé el resultado
        response = requests.get(url, params=params)
        if response.status_code != 200:
            print("Error en la llamada a Deezer:", response.status_code)    # Si falla lo va a informar
            return pd.DataFrame([])                                         # Y también nos va a devolver el DF vacío
        data = response.json()                                              # Si no falla da la respuesta en json
    except Error as e:
        print("Error en la llamada a Deezer:", e)                           # Para que nos diga exactamente cuál es el error
        return pd.DataFrame([])

    canciones = data.get("data", [])                # Obtiene la lista de canciones
    lista_canciones = []                            # Lista donde se van a acumular las filas para el DF final

    for cancion in canciones:                       # Bucle para que itere con todas las canciones y nos vaya dando los datos
        track_id = cancion["id"]                    # Nos da el id de la canción
        track = requests.get(f"https://api.deezer.com/track/{track_id}").json()  # Pide todos los datos que estén en track
        album = requests.get(f"https://api.deezer.com/album/{track['album']['id']}").json() # Pide todos los datos que estén en album

        genre_id = album.get("genre_id")   # Extrae el ID del género de album
        genre_name = None                  # Creamos la variable "vacía"
        if album.get("genres") and album["genres"].get("data"):   # Le decimoa que en el caso de que genres exista en album
            genre_name = album["genres"]["data"][0].get("name")   # Entonces nos diga el primer género que aparezca (por si hay varios)

        tracks_type = "colaboracion" if len(track.get("contributors", [])) > 1 else album.get("record_type", "track")
        # Buscamos colaboraciones. Para ello, si en contributor aparece más de 1, entonces se trata de una colaboración
        # Si no, le decimos que nos ponga lo que aparezca en record_type que es single o album, y si no que ponga track
        release_year = track.get("release_date", "")[:4] if track.get("release_date") else None
        # Obtiene el año de lanzamiento solo si hay 4 cifras, si no pondrá None 
        lista_canciones.append({                   # Creamos un diccionario para añadir todos los datos que necesitamos
            "id_artista": track["artist"]["id"],
            "nombre_artista": artist_name,
            "titulo_cancion": track["title"],
            "titulo_album": track["album"]["title"],
            "tipo": tracks_type,
            "año_lanzamiento": release_year,
            "genero": genre_name,
            "id_genero": genre_id,
        })

    return pd.DataFrame(lista_canciones)        # Hacemos que nos devuelta el resultado en un DF

df_artista = conseguir_canciones("Aretha Franklin", limit=50)
df_artista

,id_artista,nombre_artista,titulo_cancion,titulo_album,tipo,año_lanzamiento,genero,id_genero
0,2059,Aretha Franklin,Respect,I Never Loved a Man the Way I Love You,album,1995,Pop,132
1,2059,Aretha Franklin,I Say a Little Prayer,Soul Queen,album,2007,Pop,132
2,2059,Aretha Franklin,Think,Aretha Now,album,1993,Pop,132
3,2059,Aretha Franklin,(You Make Me Feel Like) A Natural Woman,Lady Soul (With Bonus Selections),album,1987,Pop,132
4,2708,Aretha Franklin,Think,The Blues Brothers Original Motion Picture Sou...,colaboracion,2011,Pop,132
5,2059,Aretha Franklin,Today I Sing the Blues (Remastered),The Very Best of Blues : 50 Unforgettable Trac...,album,2013,Rock,152
6,264516192,Aretha Franklin,I Knew You Were Waiting (For Me),Aretha (Expanded Edition),colaboracion,1986,R&B,165
7,2059,Aretha Franklin,I Never Loved a Man (The Way I Love You),I Never Loved a Man the Way I Love You,album,1995,Pop,132
8,2059,Aretha Franklin,Respect,Soul Queen,album,2007,Pop,132
9,2059,Aretha Franklin,Chain of Fools,Soul Queen,album,2007,Pop,132
10,2059,Aretha Franklin,People Get Ready,The Queen Of Soul,album,2014,R&B,165
11,2059,Aretha Franklin,"Young, Gifted and Black","Young, Gifted and Black",album,1993,Pop,132
12,2059,Aretha Franklin,One Step Ahead,A Bit Of Soul,album,1996,R&B,165
13,2059,Aretha Franklin,Rock Steady,Soul Queen,album,2007,Pop,132
14,2059,Aretha Franklin,(You Make Me Feel Like) a Natural Woman [with ...,A Brand New Me: Aretha Franklin (with The Roya...,colaboracion,2017,R&B,165
15,2059,Aretha Franklin,Freeway Of Love,Who's Zoomin' Who? (Expanded Edition),album,1985,R&B,165
16,2059,Aretha Franklin,I Will Survive (The Aretha Version),Aretha Franklin Sings The Great Diva Classics,album,2014,R&B,165
17,2059,Aretha Franklin,How I Got Over (Live at New Temple Missionary ...,How I Got Over (Live at New Temple Missionary ...,single,2019,R&B,165
18,2059,Aretha Franklin,Save Me,Soul Queen,album,2007,Pop,132
19,2059,Aretha Franklin,Get It Right,Get It Right,album,1983,R&B,165
20,2059,Aretha Franklin,Another Night,Who's Zoomin' Who?,album,2001,Rap/Hip Hop,116
21,2059,Aretha Franklin,"Baby, Baby, Baby",I Never Loved a Man the Way I Love You,album,1995,Pop,132
22,2059,Aretha Franklin,"Baby, I Love You",Soul Queen,album,2007,Pop,132
23,2059,Aretha Franklin,You Made Me Love You,The Electrifying Aretha Franklin (Expanded Edi...,album,1962,R&B,165
24,2059,Aretha Franklin,Day Dreaming,"Young, Gifted and Black",album,1993,Pop,132
25,2059,Aretha Franklin,Blue Holiday,The Electrifying Aretha Franklin (Expanded Edi...,album,1962,R&B,165
26,2059,Aretha Franklin,Try a Little Tenderness (2002 Mix),The Essential Aretha Franklin,album,2002,R&B,165
27,2059,Aretha Franklin,Operation Heartbreak,ARETHA,album,2021,R&B,165
28,2059,Aretha Franklin,Who's Zoomin' Who?,Who's Zoomin' Who?,album,2001,Rap/Hip Hop,116
29,2059,Aretha Franklin,Rolling In the Deep (The Aretha Version),Aretha Franklin Sings The Great Diva Classics,album,2014,R&B,165
30,175,Aretha Franklin,Sisters Are Doin' It for Themselves,Greatest Hits,colaboracion,1991,Pop,132
31,2059,Aretha Franklin,Won't Be Long (As heard in the Netflix series ...,Aretha In Person with The Ray Bryant Combo (Ex...,album,2025,R&B,165
32,2059,Aretha Franklin,Respect (with The Royal Philharmonic Orchestra),A Brand New Me: Aretha Franklin (with The Roya...,colaboracion,2017,R&B,165
33,2059,Aretha Franklin,Spanish Harlem,The Queen Of Soul,album,2014,R&B,165
34,2059,Aretha Franklin,I Never Loved a Man (The Way I Love You),Soul Queen,album,2007,Pop,132
35,2059,Aretha Franklin,The Weight,Soul Queen,album,2007,Pop,132
36,2059,Aretha Franklin,Skylark,Laughing On the Outside (Expanded Edition),album,1963,R&B,165
37,2059,Aretha Franklin,It's My Turn,Love All The Hurt Away,album,1981,R&B,165
38,2059,Aretha Franklin,Wonderful,So Damn Happy,album,2003,R&B,165
39,2059,Aretha Franklin,What a Diff'rence a Day Made (2002 Mix),The Essential Aretha Franklin,album,2002,R&B,165
40,2059,Aretha Franklin,You'll Lose a Good Thing,Runnin' Out of Fools (Expanded Edition),album,1964,R&B,165
41,2059,Aretha Franklin,What a Fool Believes,Aretha,album,1980,R&B,165
42,2059,Aretha Franklin,Border Song (Holy Moses) (with The Royal Philh...,A Brand New Me: Aretha Franklin (with The Roya...,colaboracion,2017,R&B,165
43,2059,Aretha Franklin,Oh Happy Day (Live at New Bethel Baptist Churc...,"One Lord, One Faith, One Baptism",colaboracion,1987,NaN,-1
44,2059,Aretha Franklin,You're a Sweet Sweet Man,Aretha Now,album,1993,Pop,132
45,2059,Aretha Franklin,Here We Go Again,A Rose Is Still A Rose,album,1998,R&B,165
46,2059,Aretha Franklin,Son of a Preacher Man,The Queen of Soul,album,2018,R&B,165
47,2059,Aretha Franklin,It Ain't Necessarily So,Aretha In Person with The Ray Bryant Combo (Ex...,album,2025,R&B,165
48,2059,Aretha Franklin,A Rose Is Still a Rose,A Rose Is Still A Rose,album,1998,R&B,165
49,2059,Aretha Franklin,Let It Be,Soul Queen,album,2007,Pop,132

In [7]:
df_artista.to_csv("aretha.csv", index=False)

In [8]:
def conseguir_canciones(artist_name, limit=50):     # Función para conseguir 50 canciones de la artista que quieras
    url = "https://api.deezer.com/search"           # URL base de la API para buscar
    params = {                                      # Para insertar los parámetros de la búsqueda
        "q": f'artist:"{artist_name}"',             # La API busca artista por q
        "limit": limit                              # Limit sirve para que saque solo 50
    }
    try:                                            # Bloque try/excep para llamar a la API y que nos dé el resultado
        response = requests.get(url, params=params)
        if response.status_code != 200:
            print("Error en la llamada a Deezer:", response.status_code)    # Si falla lo va a informar
            return pd.DataFrame([])                                         # Y también nos va a devolver el DF vacío
        data = response.json()                                              # Si no falla da la respuesta en json
    except Error as e:
        print("Error en la llamada a Deezer:", e)                           # Para que nos diga exactamente cuál es el error
        return pd.DataFrame([])

    canciones = data.get("data", [])                # Obtiene la lista de canciones
    lista_canciones = []                            # Lista donde se van a acumular las filas para el DF final

    for cancion in canciones:                       # Bucle para que itere con todas las canciones y nos vaya dando los datos
        track_id = cancion["id"]                    # Nos da el id de la canción
        track = requests.get(f"https://api.deezer.com/track/{track_id}").json()  # Pide todos los datos que estén en track
        album = requests.get(f"https://api.deezer.com/album/{track['album']['id']}").json() # Pide todos los datos que estén en album

        genre_id = album.get("genre_id")   # Extrae el ID del género de album
        genre_name = None                  # Creamos la variable "vacía"
        if album.get("genres") and album["genres"].get("data"):   # Le decimoa que en el caso de que genres exista en album
            genre_name = album["genres"]["data"][0].get("name")   # Entonces nos diga el primer género que aparezca (por si hay varios)

        tracks_type = "colaboracion" if len(track.get("contributors", [])) > 1 else album.get("record_type", "track")
        # Buscamos colaboraciones. Para ello, si en contributor aparece más de 1, entonces se trata de una colaboración
        # Si no, le decimos que nos ponga lo que aparezca en record_type que es single o album, y si no que ponga track
        release_year = track.get("release_date", "")[:4] if track.get("release_date") else None
        # Obtiene el año de lanzamiento solo si hay 4 cifras, si no pondrá None 
        lista_canciones.append({                   # Creamos un diccionario para añadir todos los datos que necesitamos
            "id_artista": track["artist"]["id"],
            "nombre_artista": artist_name,
            "titulo_cancion": track["title"],
            "titulo_album": track["album"]["title"],
            "tipo": tracks_type,
            "año_lanzamiento": release_year,
            "genero": genre_name,
            "id_genero": genre_id,
        })

    return pd.DataFrame(lista_canciones)        # Hacemos que nos devuelta el resultado en un DF

df_artista = conseguir_canciones("Lola Flores", limit=50)
df_artista

,id_artista,nombre_artista,titulo_cancion,titulo_album,tipo,año_lanzamiento,genero,id_genero
0,93523,Lola Flores,Limosna De Amores,Canta,album,2025,Latino,197
1,93523,Lola Flores,Capri C'est Fini,"Lola Flores: Sus Mejores Exitos, Vol. 1",album,2006,NaN,-1
2,93523,Lola Flores,A Tu Vera (Remastered),Grabaciones Completas (Remastered),album,2018,Flamenco,36
3,93523,Lola Flores,Como Me las Maravillaría Yo,"Todos Sus Exitos, Vol. 1",album,1994,Latino,197
4,93523,Lola Flores,Historia de un Amor (Remastered),Grabaciones Completas (Remastered),album,2018,Flamenco,36
5,93523,Lola Flores,Adoro,La Légende...,album,2011,NaN,-1
6,93523,Lola Flores,El Meneito,Mitos de la Musica Española : Lola Flores y An...,colaboracion,2000,NaN,-1
7,93523,Lola Flores,Que Me Coma el Tigre (Remastered),Grabaciones Completas (Remastered),album,2018,Flamenco,36
8,93523,Lola Flores,Díme,"Antonio Gonzalez ""El Pescailla""",colaboracion,1989,NaN,-1
9,93523,Lola Flores,"Ay, pena, penita, pena","Ay Pena, Penita, Pena",single,2007,Pop,132
10,93523,Lola Flores,Amaneci En Tus Brazos,Best Of,album,2011,NaN,-1
11,71805,Lola Flores,Madrid (Remastered),Grabaciones Completas (Remastered),colaboracion,2018,NaN,-1
12,93523,Lola Flores,La Niña De Fuego,"Lola Flores, Sus 20 Grandes Éxitos",album,2008,Flamenco,36
13,93523,Lola Flores,A Tu Vera,"La Copla, Siempre",album,2020,Flamenco,36
14,93523,Lola Flores,La luna y el toro,"La Copla, Vol. 8",album,1991,NaN,-1
15,93523,Lola Flores,Tanguillo de la Guapa de Cadiz,De cerca,album,2026,NaN,-1
16,93523,Lola Flores,Te Amaré Toda la Vida (Remastered),Grabaciones Completas (Remastered),album,2018,Flamenco,36
17,93523,Lola Flores,La Zarzamora (Remastered),La Zarzamora (Remastered),album,2019,Flamenco,36
18,93523,Lola Flores,Pena Penita Pena,Lola de España,album,2014,Flamenco,36
19,93523,Lola Flores,Federico García Lorca (Fragmentos),Por Siempre Lola,album,2020,Flamenco,36
20,93523,Lola Flores,La bomba gitana,"La Copla, Vol. 8",album,1991,NaN,-1
21,93523,Lola Flores,Pan y Chocolate,Por Siempre Lola,colaboracion,2020,Flamenco,36
22,93523,Lola Flores,Al Verde Limon Lola Flores,El Televisor Rumba,album,2019,Jazz,129
23,93523,Lola Flores,Mi Sangre Mora,La Inimitable,album,1991,Latino,197
24,93523,Lola Flores,Rosa Candelaria (Remastered),A tu vera (Remastered),album,2019,Flamenco,36
25,93523,Lola Flores,Mía,Mitos de la Musica Española : Lola Flores y An...,colaboracion,2000,NaN,-1
26,93523,Lola Flores,Alguien Cantó,Grandes de España,colaboracion,2015,Flamenco,36
27,93523,Lola Flores,Dolores la Golondrina (Remastered),Grabaciones Completas (Remastered),album,2018,Flamenco,36
28,93523,Lola Flores,María bonita (Remastered),A tu vera (Remastered),album,2021,NaN,-1
29,93523,Lola Flores,"Ay Pena, Penita, Pena","Lola Flores, Sus 20 Grandes Éxitos",album,2008,Flamenco,36
30,93523,Lola Flores,Lola de España,"La Copla, Siempre",album,2020,Flamenco,36
31,93523,Lola Flores,Cuatro Sevillanas De Baile,El Televisor Rumba,album,2019,Jazz,129
32,93523,Lola Flores,Torbellino de Colores (Remastered),Grabaciones Completas (Remastered),album,2018,Flamenco,36
33,93523,Lola Flores,Coplas por Bulería,"Raíces de la Canción Española, Vol. 39",album,1998,NaN,-1
34,93523,Lola Flores,El Toro y la Luna (Remastered),Grabaciones Completas (Remastered),album,2018,Flamenco,36
35,93523,Lola Flores,Pa Su Papá,La Copla Española Vol. 32,album,2012,NaN,-1
36,93523,Lola Flores,El Despertador,"Lola Flores, Sus 20 Grandes Éxitos",album,2008,Flamenco,36
37,93523,Lola Flores,Mora gitana (Remastered),Échale guindas al pavo (Remastered),ep,2023,Latino,197
38,93523,Lola Flores,Al Verde Limon,El Televisor Rumba,album,2019,Jazz,129
39,93523,Lola Flores,Lola Lolita,De cerca,colaboracion,2026,NaN,-1
40,93523,Lola Flores,Catallina Fernández la lotera (Remastered),A tu vera (Remastered),album,2019,Flamenco,36
41,93523,Lola Flores,Tu engaño,Lola de España,album,2006,Latino,197
42,93523,Lola Flores,La Maravilla,Homenaje,album,1995,Pop,132
43,93523,Lola Flores,Pepa Bandera,Grandes de la Copla,album,2014,NaN,-1
44,93523,Lola Flores,Angustias Sánchez,Lola Flores - The Essential,album,2022,Flamenco,36
45,93523,Lola Flores,Tu Caballo (Remastered),Grabaciones Completas (Remastered),album,2018,Flamenco,36
46,93523,Lola Flores,No Me Llames Dolores (Remastered),Grabaciones Completas (Remastered),album,2018,Flamenco,36
47,93523,Lola Flores,Tientos del sombrero (Remastered),Jerezana (Remastered),ep,2023,Latino,197
48,93523,Lola Flores,Espinita,Sus Grandes Exitos en America,album,2015,Flamenco,36
49,93523,Lola Flores,Echale Guindas al Pavo (Remastered),The Best of Lola Flores (Remastered),album,2019,Flamenco,36

In [9]:
df_artista.to_csv("lola.csv", index=False)

In [10]:
def conseguir_canciones(artist_name, limit=50):     # Función para conseguir 50 canciones de la artista que quieras
    url = "https://api.deezer.com/search"           # URL base de la API para buscar
    params = {                                      # Para insertar los parámetros de la búsqueda
        "q": f'artist:"{artist_name}"',             # La API busca artista por q
        "limit": limit                              # Limit sirve para que saque solo 50
    }
    try:                                            # Bloque try/excep para llamar a la API y que nos dé el resultado
        response = requests.get(url, params=params)
        if response.status_code != 200:
            print("Error en la llamada a Deezer:", response.status_code)    # Si falla lo va a informar
            return pd.DataFrame([])                                         # Y también nos va a devolver el DF vacío
        data = response.json()                                              # Si no falla da la respuesta en json
    except Error as e:
        print("Error en la llamada a Deezer:", e)                           # Para que nos diga exactamente cuál es el error
        return pd.DataFrame([])

    canciones = data.get("data", [])                # Obtiene la lista de canciones
    lista_canciones = []                            # Lista donde se van a acumular las filas para el DF final

    for cancion in canciones:                       # Bucle para que itere con todas las canciones y nos vaya dando los datos
        track_id = cancion["id"]                    # Nos da el id de la canción
        track = requests.get(f"https://api.deezer.com/track/{track_id}").json()  # Pide todos los datos que estén en track
        album = requests.get(f"https://api.deezer.com/album/{track['album']['id']}").json() # Pide todos los datos que estén en album

        genre_id = album.get("genre_id")   # Extrae el ID del género de album
        genre_name = None                  # Creamos la variable "vacía"
        if album.get("genres") and album["genres"].get("data"):   # Le decimoa que en el caso de que genres exista en album
            genre_name = album["genres"]["data"][0].get("name")   # Entonces nos diga el primer género que aparezca (por si hay varios)

        tracks_type = "colaboracion" if len(track.get("contributors", [])) > 1 else album.get("record_type", "track")
        # Buscamos colaboraciones. Para ello, si en contributor aparece más de 1, entonces se trata de una colaboración
        # Si no, le decimos que nos ponga lo que aparezca en record_type que es single o album, y si no que ponga track
        release_year = track.get("release_date", "")[:4] if track.get("release_date") else None
        # Obtiene el año de lanzamiento solo si hay 4 cifras, si no pondrá None 
        lista_canciones.append({                   # Creamos un diccionario para añadir todos los datos que necesitamos
            "id_artista": track["artist"]["id"],
            "nombre_artista": artist_name,
            "titulo_cancion": track["title"],
            "titulo_album": track["album"]["title"],
            "tipo": tracks_type,
            "año_lanzamiento": release_year,
            "genero": genre_name,
            "id_genero": genre_id,
        })

    return pd.DataFrame(lista_canciones)        # Hacemos que nos devuelta el resultado en un DF

df_artista = conseguir_canciones("Nina Simone", limit=50)
df_artista

,id_artista,nombre_artista,titulo_cancion,titulo_album,tipo,año_lanzamiento,genero,id_genero
0,744,Nina Simone,Feeling Good,Feeling Good: The Very Best Of Nina Simone,album,2019,Jazz,129
1,744,Nina Simone,I Put A Spell On You,I Put A Spell On You,album,2018,Jazz,129
2,744,Nina Simone,One September Day,I Put A Spell On You,album,2018,Jazz,129
3,744,Nina Simone,Here Comes the Sun,The Very Best Of Nina Simone 1967-1972 - Sugar...,album,1998,Jazz,129
4,744,Nina Simone,Sinnerman,Feeling Good: The Very Best Of Nina Simone,album,2019,Jazz,129
5,744,Nina Simone,Sinnerman (Sofi Tukker Remix),Sinnerman (Sofi Tukker Remix),colaboracion,2021,Jazz,129
6,744,Nina Simone,Sinnerman (Felix Da Housecat's Heavenly House ...,Verve Remixed 2,colaboracion,2007,Jazz,129
7,744,Nina Simone,My Baby Just Cares for Me,My Baby Just Cares for Me,album,2009,Jazz,129
8,744,Nina Simone,Take Care Of Business (Solomun Mix),Take Care Of Business (Solomun Mix),colaboracion,2026,Electro,106
9,744,Nina Simone,Ain't Got No - I Got Life (From the Musical Pr...,The Greatest Hits,album,2003,Pop,132
10,744,Nina Simone,Blues for Mama,Nina Simone Sings The Blues (Expanded Edition),album,2006,Jazz,129
11,744,Nina Simone,I Wish I Knew How It Would Feel to Be Free,Silk & Soul (Expanded Edition),album,2006,Jazz,129
12,744,Nina Simone,Baltimore,Baltimore,album,1995,Jazz,129
13,744,Nina Simone,My Way,Here Comes The Sun (Expanded Edition),album,2012,Jazz,129
14,744,Nina Simone,To Love Somebody,The Greatest Hits,album,2003,Pop,132
15,744,Nina Simone,Don't Let Me Be Misunderstood,Don't Let Me Be Misunderstood,album,2018,Jazz,129
16,744,Nina Simone,Feeling Good (Joe Claussell Remix),Remixed,ep,2021,Jazz,129
17,744,Nina Simone,Tell It Like It Is,The Very Best Of Nina Simone 1967-1972 - Sugar...,album,1998,Jazz,129
18,744,Nina Simone,Mr. Bojangles,The Greatest Hits,album,2003,Pop,132
19,744,Nina Simone,Ne Me Quitte Pas,Don't Let Me Be Misunderstood,album,2018,Jazz,129
20,744,Nina Simone,I Wish I Knew How It Would Feel to be Free (St...,Studio Rio Presents: The Brazil Connection,colaboracion,2014,Jazz,129
21,744,Nina Simone,Work Song,High Priestess Of Soul,album,2007,Jazz,129
22,744,Nina Simone,Four Women (DESIREE Remix),Four Women (DESIREE Remix),colaboracion,2026,Electro,106
23,744,Nina Simone,Since I Fell for You,The Greatest Hits,album,2003,Pop,132
24,744,Nina Simone,My Baby Just Cares For Me (HONNE Remix),My Baby Just Cares For Me (HONNE Remix),colaboracion,2022,Jazz,129
25,744,Nina Simone,Funkier Than a Mosquito's Tweeter,It Is Finished (Expanded Edition),album,2012,Jazz,129
26,744,Nina Simone,My Way,Feeling Good The Best Of Nina Simone,album,2011,NaN,-1
27,744,Nina Simone,Feeling Good (Austin Millz Remix),Feeling Good (Austin Millz Remix),colaboracion,2022,Dance,113
28,744,Nina Simone,I Shall Be Released,To Love Somebody (Expanded Edition),album,1969,Jazz,129
29,744,Nina Simone,I Got It Bad (And That Ain't Good),The Best Of - The Colpix Years,album,1992,Jazz,129
30,744,Nina Simone,Chilly Winds Don't Blow (Bolden. Remix),Chilly Winds Don't Blow (Bolden. Remix),colaboracion,2025,Jazz,129
31,744,Nina Simone,Nobody's Fault But Mine,The Greatest Hits,album,2003,Pop,132
32,744,Nina Simone,I Want a Little Sugar In My Bowl,Nina Simone Sings The Blues (Expanded Edition),album,2006,Jazz,129
33,744,Nina Simone,My Baby Just Cares For Me (Live At Vine St. Ba...,Spotlight on Nina Simone,album,2020,Jazz,129
34,744,Nina Simone,Here Comes the Sun,The Greatest Hits,album,2003,Pop,132
35,744,Nina Simone,Ain't Got No - I Got Life (From the Musical Pr...,The Very Best Of Nina Simone 1967-1972 - Sugar...,album,1998,Jazz,129
36,744,Nina Simone,Black Is The Color Of My True Love's Hair,Wild Is The Wind,album,2018,Jazz,129
37,744,Nina Simone,Turn Me On,The Greatest Hits,album,2003,Pop,132
38,744,Nina Simone,The Look of Love,The Greatest Hits,album,2003,Pop,132
39,744,Nina Simone,Suzanne,The Greatest Hits,album,2003,Pop,132
40,744,Nina Simone,Do I Move You? (Version II),The Greatest Hits,album,2003,Pop,132
41,744,Nina Simone,Tomorrow Is My Turn,I Put A Spell On You,album,2018,Jazz,129
42,744,Nina Simone,It Be's That Way Sometime,Silk & Soul (Expanded Edition),album,2006,Jazz,129
43,744,Nina Simone,Backlash Blues,The Very Best Of Nina Simone 1967-1972 - Sugar...,album,1998,Jazz,129
44,744,Nina Simone,The House of the Rising Sun,Nina Simone Sings The Blues (Expanded Edition),album,2006,Jazz,129
45,744,Nina Simone,"My Man's Gone Now (From ""Porgy and Bess"")",The Greatest Hits,album,2003,Pop,132
46,744,Nina Simone,Do What You Gotta Do,The Greatest Hits,album,2003,Pop,132
47,744,Nina Simone,I Get Along Without You Very Well (Except Some...,The Very Best Of Nina Simone 1967-1972 - Sugar...,album,1998,Jazz,129
48,744,Nina Simone,Take Care Of Business,Gold,album,2018,Pop,132
49,744,Nina Simone,See-Line Woman (Mochakk Mix / Edit),See-Line Woman (Mochakk Mix),colaboracion,2026,Electro,106

In [11]:
df_artista.to_csv("nina.csv", index=False)

In [12]:
def conseguir_canciones(artist_name, limit=50):     # Función para conseguir 50 canciones de la artista que quieras
    url = "https://api.deezer.com/search"           # URL base de la API para buscar
    params = {                                      # Para insertar los parámetros de la búsqueda
        "q": f'artist:"{artist_name}"',             # La API busca artista por q
        "limit": limit                              # Limit sirve para que saque solo 50
    }
    try:                                            # Bloque try/excep para llamar a la API y que nos dé el resultado
        response = requests.get(url, params=params)
        if response.status_code != 200:
            print("Error en la llamada a Deezer:", response.status_code)    # Si falla lo va a informar
            return pd.DataFrame([])                                         # Y también nos va a devolver el DF vacío
        data = response.json()                                              # Si no falla da la respuesta en json
    except Error as e:
        print("Error en la llamada a Deezer:", e)                           # Para que nos diga exactamente cuál es el error
        return pd.DataFrame([])

    canciones = data.get("data", [])                # Obtiene la lista de canciones
    lista_canciones = []                            # Lista donde se van a acumular las filas para el DF final

    for cancion in canciones:                       # Bucle para que itere con todas las canciones y nos vaya dando los datos
        track_id = cancion["id"]                    # Nos da el id de la canción
        track = requests.get(f"https://api.deezer.com/track/{track_id}").json()  # Pide todos los datos que estén en track
        album = requests.get(f"https://api.deezer.com/album/{track['album']['id']}").json() # Pide todos los datos que estén en album

        genre_id = album.get("genre_id")   # Extrae el ID del género de album
        genre_name = None                  # Creamos la variable "vacía"
        if album.get("genres") and album["genres"].get("data"):   # Le decimoa que en el caso de que genres exista en album
            genre_name = album["genres"]["data"][0].get("name")   # Entonces nos diga el primer género que aparezca (por si hay varios)

        tracks_type = "colaboracion" if len(track.get("contributors", [])) > 1 else album.get("record_type", "track")
        # Buscamos colaboraciones. Para ello, si en contributor aparece más de 1, entonces se trata de una colaboración
        # Si no, le decimos que nos ponga lo que aparezca en record_type que es single o album, y si no que ponga track
        release_year = track.get("release_date", "")[:4] if track.get("release_date") else None
        # Obtiene el año de lanzamiento solo si hay 4 cifras, si no pondrá None 
        lista_canciones.append({                   # Creamos un diccionario para añadir todos los datos que necesitamos
            "id_artista": track["artist"]["id"],
            "nombre_artista": artist_name,
            "titulo_cancion": track["title"],
            "titulo_album": track["album"]["title"],
            "tipo": tracks_type,
            "año_lanzamiento": release_year,
            "genero": genre_name,
            "id_genero": genre_id,
        })

    return pd.DataFrame(lista_canciones)        # Hacemos que nos devuelta el resultado en un DF

df_artista = conseguir_canciones("Sylvie Vartan", limit=50)
df_artista

,id_artista,nombre_artista,titulo_cancion,titulo_album,tipo,año_lanzamiento,genero,id_genero
0,11440,Sylvie Vartan,La Maritza,La Maritza,album,2026,Pop,132
1,11440,Sylvie Vartan,L'amour c'est comme une cigarette,Le meilleur des années RCA,album,2026,Pop,132
2,11440,Sylvie Vartan,La plus belle pour aller danser,La plus belle pour aller danser,ep,2026,Pop,132
3,11440,Sylvie Vartan,La plus belle pour aller danser,Sylvie Vartan,album,1995,Pop,132
4,13314683,Sylvie Vartan,Baby c'est vous,Rivages,colaboracion,2024,Electro,106
5,11440,Sylvie Vartan,Irrésistiblement,Les années RCA (Vol. 3),album,2026,Pop,132
6,11440,Sylvie Vartan,Comme un garçon,Le meilleur des années RCA,album,2026,Pop,132
7,11440,Sylvie Vartan,Ne t'en va pas,Twiste et chante,album,2026,Pop,132
8,11440,Sylvie Vartan,La drôle de fin (Last Tango),Qu'est ce qui fait pleurer les blondes?,album,2026,Pop,132
9,11440,Sylvie Vartan,Qu'est ce qui fait pleurer les blondes (Ride t...,Triple Best Of,album,2026,Pop,132
10,1060,Sylvie Vartan,J'ai un problème,Best Of 70,colaboracion,2014,Pop,132
11,11440,Sylvie Vartan,La Maritza,Sylvie Vartan,album,1995,Pop,132
12,11440,Sylvie Vartan,Si je chante (Remastered),Si je chante (Remastered),ep,2014,Pop,132
13,11440,Sylvie Vartan,L'amour c'est comme une cigarette,Une vie en musique,album,2015,NaN,-1
14,11440,Sylvie Vartan,Petit rainbow (Summer Love Sensation),Georges,album,2026,Pop,132
15,11440,Sylvie Vartan,Baby c'est vous,Baby c’est vous,ep,2026,Pop,132
16,11440,Sylvie Vartan,En écoutant la pluie,Triple Best Of,album,2026,Pop,132
17,11440,Sylvie Vartan,Sang pour sang,Avec toi...,album,2018,NaN,-1
18,4509,Sylvie Vartan,La première fois qu'on s'aimera,Les années 30,colaboracion,2018,Pop,132
19,11440,Sylvie Vartan,Nicolas,Déraisonnable,album,2026,Pop,132
20,11440,Sylvie Vartan,La Maritza (Extended Andréas Rework),La Maritza (Extended Andréas Rework),single,2026,Pop,132
21,11440,Sylvie Vartan,Ballade pour un sourire,Les années RCA (Vol. 2),album,2026,Pop,132
22,1060,Sylvie Vartan,"L'hymne à l'amour / Non, je ne regrette rien (...",Sylvie Live,colaboracion,2010,NaN,-1
23,11440,Sylvie Vartan,La Maritza (Andréas Rework) (Andréas Rework),La Maritza (Andréas Rework),single,2026,Pop,132
24,11440,Sylvie Vartan,Georges (George Disco Tango),Georges,album,2026,Pop,132
25,11440,Sylvie Vartan,Aimer,Triple Best Of,album,2026,Pop,132
26,11440,Sylvie Vartan,Toi jamais,Qu'est ce qui fait pleurer les blondes?,album,2026,Pop,132
27,11440,Sylvie Vartan,Chanson de l'autruche (Version edit),Emilie Jolie (Version originale),album,2021,NaN,-1
28,11440,Sylvie Vartan,"Par amour, par pitié",Sylvie (2'35 de bonheur),album,2026,Pop,132
29,11440,Sylvie Vartan,Toi le garçon,Le meilleur des années RCA,album,2026,Pop,132
30,11440,Sylvie Vartan,Déprime,Danse ta vie,album,2026,Pop,132
31,11440,Sylvie Vartan,En écoutant la pluie,Une vie en musique,album,2015,NaN,-1
32,11440,Sylvie Vartan,"Georges (Intégrale Live - Palais des Congrès, ...",L'intégrale live,album,2026,Pop,132
33,11440,Sylvie Vartan,Comme un garçon,Une vie en musique,album,2015,NaN,-1
34,11440,Sylvie Vartan,L'Orient-Express,Une vie en musique,album,2015,NaN,-1
35,11440,Sylvie Vartan,Je chante encore l'amour,Fantaisie,album,2026,Pop,132
36,11440,Sylvie Vartan,Due minuti di felicità,Se io canto,album,2026,Pop,132
37,11440,Sylvie Vartan,Moi je pense encore a toi (Remastered),Moi je pense encore à toi (Remastered),ep,2022,Pop,132
38,11440,Sylvie Vartan,Baby C'est Vous,Sylvie,album,1962,Pop,132
39,11440,Sylvie Vartan,2'35 de bonheur,Sylvie (2'35 de bonheur),album,2026,Pop,132
40,11440,Sylvie Vartan,Les moulins de mon coeur (The Windmills of You...,La reine de Saba,album,2026,Pop,132
41,11440,Sylvie Vartan,Tous Mes Copains,La Panne D'essence,single,2014,NaN,-1
42,11440,Sylvie Vartan,Nicolas,Une vie en musique,album,2015,NaN,-1
43,11440,Sylvie Vartan,La drôle de fin,Une vie en musique,album,2015,NaN,-1
44,11440,Sylvie Vartan,Danse ta vie,Triple Best Of,album,2026,Pop,132
45,11440,Sylvie Vartan,Le Loco-Motion (The Locomotion),Sylvie! 1961-62,album,2018,Pop,132
46,11440,Sylvie Vartan,Tu n'as rien compris,Virage,album,2026,Pop,132
47,11440,Sylvie Vartan,La musique que j'aime,Avec toi...,album,2018,NaN,-1
48,11440,Sylvie Vartan,L'amour c'est comme les bateaux,Ta sorcière bien-aimée,album,2026,Pop,132
49,11440,Sylvie Vartan,Soleil bleu,Soleil bleu,colaboracion,2010,NaN,-1

In [13]:
df_artista.to_csv("silvie.csv", index=False)

In [14]:
def conseguir_canciones(artist_name, limit=50):     # Función para conseguir 50 canciones de la artista que quieras
    url = "https://api.deezer.com/search"           # URL base de la API para buscar
    params = {                                      # Para insertar los parámetros de la búsqueda
        "q": f'artist:"{artist_name}"',             # La API busca artista por q
        "limit": limit                              # Limit sirve para que saque solo 50
    }
    try:                                            # Bloque try/excep para llamar a la API y que nos dé el resultado
        response = requests.get(url, params=params)
        if response.status_code != 200:
            print("Error en la llamada a Deezer:", response.status_code)    # Si falla lo va a informar
            return pd.DataFrame([])                                         # Y también nos va a devolver el DF vacío
        data = response.json()                                              # Si no falla da la respuesta en json
    except Error as e:
        print("Error en la llamada a Deezer:", e)                           # Para que nos diga exactamente cuál es el error
        return pd.DataFrame([])

    canciones = data.get("data", [])                # Obtiene la lista de canciones
    lista_canciones = []                            # Lista donde se van a acumular las filas para el DF final

    for cancion in canciones:                       # Bucle para que itere con todas las canciones y nos vaya dando los datos
        track_id = cancion["id"]                    # Nos da el id de la canción
        track = requests.get(f"https://api.deezer.com/track/{track_id}").json()  # Pide todos los datos que estén en track
        album = requests.get(f"https://api.deezer.com/album/{track['album']['id']}").json() # Pide todos los datos que estén en album

        genre_id = album.get("genre_id")   # Extrae el ID del género de album
        genre_name = None                  # Creamos la variable "vacía"
        if album.get("genres") and album["genres"].get("data"):   # Le decimoa que en el caso de que genres exista en album
            genre_name = album["genres"]["data"][0].get("name")   # Entonces nos diga el primer género que aparezca (por si hay varios)

        tracks_type = "colaboracion" if len(track.get("contributors", [])) > 1 else album.get("record_type", "track")
        # Buscamos colaboraciones. Para ello, si en contributor aparece más de 1, entonces se trata de una colaboración
        # Si no, le decimos que nos ponga lo que aparezca en record_type que es single o album, y si no que ponga track
        release_year = track.get("release_date", "")[:4] if track.get("release_date") else None
        # Obtiene el año de lanzamiento solo si hay 4 cifras, si no pondrá None 
        lista_canciones.append({                   # Creamos un diccionario para añadir todos los datos que necesitamos
            "id_artista": track["artist"]["id"],
            "nombre_artista": artist_name,
            "titulo_cancion": track["title"],
            "titulo_album": track["album"]["title"],
            "tipo": tracks_type,
            "año_lanzamiento": release_year,
            "genero": genre_name,
            "id_genero": genre_id,
        })

    return pd.DataFrame(lista_canciones)        # Hacemos que nos devuelta el resultado en un DF

df_artista = conseguir_canciones("Patty Pravo", limit=50)
df_artista

,id_artista,nombre_artista,titulo_cancion,titulo_album,tipo,año_lanzamiento,genero,id_genero
0,58615,Patty Pravo,La bambola,Aristocratica,album,1998,Pop,132
1,58615,Patty Pravo,...dimmi che non vuoi morire,Bye bye patty,album,1997,Pop,132
2,58615,Patty Pravo,La bambola,Patty Pravo,album,2000,Pop,132
3,58615,Patty Pravo,Lettera a Gianni,Patty Pravo - Rarities 1967,album,2017,Pop,132
4,58615,Patty Pravo,Pazza idea,Anni Settanta,album,2007,Pop,132
5,58615,Patty Pravo,La Spada Nel Cuore,Mi ritorni in mente...i successi degli anni '70,album,2007,Pop,132
6,58615,Patty Pravo,Il paradiso,Patty Pravo - I Miti,album,1999,Pop,132
7,58615,Patty Pravo,Tutt'al più,Patty Pravo - I Miti,album,1999,Pop,132
8,58615,Patty Pravo,I giardini di Kensington,Patty Pravo - I Miti,album,1999,Pop,132
9,58615,Patty Pravo,Morire tra le viole,Patty Pravo - I Miti,album,1999,Pop,132
10,58615,Patty Pravo,Tanto,Patty Pravo - I Miti,album,1999,Pop,132
11,58615,Patty Pravo,Io ti venderei,Patty Pravo - I Miti,album,1999,Pop,132
12,58615,Patty Pravo,Pensiero stupendo,Patty Pravo - I Miti,album,1999,Pop,132
13,58615,Patty Pravo,Lettera A Gianni,Patty Pravo - Rarities 1967,album,2017,Pop,132
14,58615,Patty Pravo,La bambola,Cuentame,album,2001,Pop,132
15,58615,Patty Pravo,Se Perdo Te,Patty Pravo,album,2000,Pop,132
16,58615,Patty Pravo,Ragazzo Triste,Patty Pravo,album,2006,Pop,132
17,153907,Patty Pravo,Bambola,Bambola,colaboracion,2017,Electro,106
18,58615,Patty Pravo,Un po' come la vita (Sanremo 2019),Red,colaboracion,2019,Pop,132
19,58615,Patty Pravo,Pensiero stupendo,Pazza idea,album,1984,Pop,132
20,58615,Patty Pravo,Cieli immensi,Cieli immensi,single,2016,Pop,132
21,58615,Patty Pravo,Love Story,Di Vero In Fondo,album,2008,Pop,132
22,58615,Patty Pravo,Massachussets,Patty Pravo - Rarities 1967,album,2017,Pop,132
23,58615,Patty Pravo,Sentimento,Patty Pravo,album,2006,Pop,132
24,58615,Patty Pravo,La bambola,Italia Romántica,compile,2016,Pop,132
25,58615,Patty Pravo,La Bambola,Solino,album,2002,Pop,132
26,153907,Patty Pravo,Bambola (Radio Version),Bambola,colaboracion,2017,Electro,106
27,58615,Patty Pravo,E dimmi che non vuoi morire,Patty Live '99,album,2001,Pop,132
28,58615,Patty Pravo,Sogno (demo),Mine Vaganti - international version,album,2010,Pop,132
29,58615,Patty Pravo,Opera,Opera,single,2026,Pop,132
30,153907,Patty Pravo,Bambola (Dub Version),Bambola,colaboracion,2017,Electro,106
31,58615,Patty Pravo,Se perdo te (Live),Patty Pravo (Live),album,2013,Pop,132
32,58615,Patty Pravo,Io ti venderei (Live),Il Meglio Di Patty Pravo: Grandi Successi,album,2016,Pop,132
33,58615,Patty Pravo,E dimmi che non vuoi morire (Live),Live Arena Di Verona,album,2013,Pop,132
34,58615,Patty Pravo,Pensiero stupendo (Live),Live Arena Di Verona,album,2013,Pop,132
35,58615,Patty Pravo,E mi manchi tanto (Live),Live Arena Di Verona,album,2013,Pop,132
36,58615,Patty Pravo,Pensiero Stupendo (French Remix),Super Best,album,2012,NaN,-1
37,58615,Patty Pravo,Ti lascio una canzone,Ti lascio una canzone,single,2026,Pop,132
38,58615,Patty Pravo,Angelus,"Notti, guai e libertà",album,1998,Pop,132
39,58615,Patty Pravo,Sogno (Live),Nella terra dei pinguini,album,2011,Pop,132
40,58615,Patty Pravo,Qui e là,Patty Pravo,album,2000,Pop,132
41,58615,Patty Pravo,Come un Pierrot,Patty Pravo,album,2002,Pop,132
42,58615,Patty Pravo,Nel giardino dell'amore,Patty Pravo,album,2002,Pop,132
43,58615,Patty Pravo,Notti bianche,Patty Pravo,album,2002,Pop,132
44,58615,Patty Pravo,Se c'è' l'amore,Patty Pravo,album,2000,Pop,132
45,58615,Patty Pravo,Sentimento,Patty Pravo,album,2000,Pop,132
46,58615,Patty Pravo,Tripoli '69,Patty Pravo,album,2000,Pop,132
47,58615,Patty Pravo,All'inferno insieme a te,Patty Pravo,album,2000,Pop,132
48,58615,Patty Pravo,Il vento e le rose,Nella terra dei pinguini,album,2011,Pop,132
49,58615,Patty Pravo,Mille lire al mese,Nella terra dei pinguini,album,2011,Pop,132

In [15]:
df_artista.to_csv("patty.csv", index=False)

In [16]:
def conseguir_canciones(artist_name, limit=50):     # Función para conseguir 50 canciones de la artista que quieras
    url = "https://api.deezer.com/search"           # URL base de la API para buscar
    params = {                                      # Para insertar los parámetros de la búsqueda
        "q": f'artist:"{artist_name}"',             # La API busca artista por q
        "limit": limit                              # Limit sirve para que saque solo 50
    }
    try:                                            # Bloque try/excep para llamar a la API y que nos dé el resultado
        response = requests.get(url, params=params)
        if response.status_code != 200:
            print("Error en la llamada a Deezer:", response.status_code)    # Si falla lo va a informar
            return pd.DataFrame([])                                         # Y también nos va a devolver el DF vacío
        data = response.json()                                              # Si no falla da la respuesta en json
    except Error as e:
        print("Error en la llamada a Deezer:", e)                           # Para que nos diga exactamente cuál es el error
        return pd.DataFrame([])

    canciones = data.get("data", [])                # Obtiene la lista de canciones
    lista_canciones = []                            # Lista donde se van a acumular las filas para el DF final

    for cancion in canciones:                       # Bucle para que itere con todas las canciones y nos vaya dando los datos
        track_id = cancion["id"]                    # Nos da el id de la canción
        track = requests.get(f"https://api.deezer.com/track/{track_id}").json()  # Pide todos los datos que estén en track
        album = requests.get(f"https://api.deezer.com/album/{track['album']['id']}").json() # Pide todos los datos que estén en album

        genre_id = album.get("genre_id")   # Extrae el ID del género de album
        genre_name = None                  # Creamos la variable "vacía"
        if album.get("genres") and album["genres"].get("data"):   # Le decimoa que en el caso de que genres exista en album
            genre_name = album["genres"]["data"][0].get("name")   # Entonces nos diga el primer género que aparezca (por si hay varios)

        tracks_type = "colaboracion" if len(track.get("contributors", [])) > 1 else album.get("record_type", "track")
        # Buscamos colaboraciones. Para ello, si en contributor aparece más de 1, entonces se trata de una colaboración
        # Si no, le decimos que nos ponga lo que aparezca en record_type que es single o album, y si no que ponga track
        release_year = track.get("release_date", "")[:4] if track.get("release_date") else None
        # Obtiene el año de lanzamiento solo si hay 4 cifras, si no pondrá None 
        lista_canciones.append({                   # Creamos un diccionario para añadir todos los datos que necesitamos
            "id_artista": track["artist"]["id"],
            "nombre_artista": artist_name,
            "titulo_cancion": track["title"],
            "titulo_album": track["album"]["title"],
            "tipo": tracks_type,
            "año_lanzamiento": release_year,
            "genero": genre_name,
            "id_genero": genre_id,
        })

    return pd.DataFrame(lista_canciones)        # Hacemos que nos devuelta el resultado en un DF

df_artista = conseguir_canciones("Rita Pavone", limit=50)
df_artista

,id_artista,nombre_artista,titulo_cancion,titulo_album,tipo,año_lanzamiento,genero,id_genero
0,77224,Rita Pavone,Cuore,31 Grandi Successi,album,2016,Pop,132
1,77224,Rita Pavone,Viva la pappa col pomodoro,Los Grandes Exitos de Rita Pavone,album,1998,Pop,132
2,77224,Rita Pavone,Amore twist,Labor day (Italian music party),album,2016,Pop,132
3,77224,Rita Pavone,Que Me Importa el Mundo,Rita Pavone canta en Espanol (Singles Collection),album,2000,Pop,132
4,77224,Rita Pavone,Il ballo del mattone,Rita Pavone (Gli Indimenticabili),album,2026,Pop,132
5,77224,Rita Pavone,Come te non c'e' nessuno,The Best of Rita Pavone,album,2014,NaN,-1
6,77224,Rita Pavone,Corazón,Sus Exitos en Español,album,1995,Latino,197
7,77224,Rita Pavone,Zucchero,Nostalgia Italiana - 1969,album,1996,Pop,132
8,77224,Rita Pavone,Viva la pappa col pomodoro,31 Grandi Successi,album,2016,Pop,132
9,77224,Rita Pavone,Che m´importa del mondo,31 Grandi Successi,album,2016,Pop,132
10,77224,Rita Pavone,Il ballo del mattone,31 Grandi Successi,album,2016,Pop,132
11,77224,Rita Pavone,El Partido De Futbol (La Partita Di Pallone),No Hay Otro Como Tu,ep,2015,Pop,132
12,77224,Rita Pavone,Che m'importa del mondo,Italia Romántica,compile,2016,Pop,132
13,77224,Rita Pavone,Cuore,Rita Pavone Rarities 1971,album,2026,Pop,132
14,77224,Rita Pavone,Solo tu (vers. Catalana),Rita Pavone Rarities 1966,album,2026,Pop,132
15,77224,Rita Pavone,Sul Cucuzzolo,Questo nostro amore,album,2026,Pop,132
16,77224,Rita Pavone,Pel Di Carota,All The Best,album,2020,Pop,132
17,77224,Rita Pavone,Plip (vers. Catalana),Rita Pavone Rarities 1966,album,2026,Pop,132
18,77224,Rita Pavone,Alla Mia Età,Ricordi d' Italia / 12,album,2018,NaN,-1
19,77224,Rita Pavone,Que Me Importa el Mundo,Piccola grande Rita,album,2026,Pop,132
20,77224,Rita Pavone,Il geghegè,31 Grandi Successi,album,2016,Pop,132
21,77224,Rita Pavone,Datemi un martello,31 Grandi Successi,album,2016,Pop,132
22,77224,Rita Pavone,Corazon,Le Canzoni di Rita Pavone,album,1961,Pop,132
23,77224,Rita Pavone,Come Te Non Ce'Nessuno,Fiesta de los 60'S,album,2017,Rock,152
24,77224,Rita Pavone,Che m'importa del mondo,Il meglio di Rita Pavone,album,2017,Pop,132
25,77224,Rita Pavone,Fortissimo,31 Grandi Successi,album,2016,Pop,132
26,77224,Rita Pavone,Little Rita,Rita Pavone 1967 (Recording Session),album,2026,Pop,132
27,77224,Rita Pavone,Como Tú No Hay Ninguno,60 Canciones de los 60,album,2014,Pop,132
28,77224,Rita Pavone,Niente (Resilienza 74),Niente (Resilienza 74),single,2026,Pop,132
29,77224,Rita Pavone,Volare,Le Canzoni di Rita Pavone,album,1961,Pop,132
30,77224,Rita Pavone,Supercalifragilìsticoespialidoso,Piccola grande Rita,album,2026,Pop,132
31,77224,Rita Pavone,Ahi ahi ragazzo,Rita Pavone,album,2026,Pop,132
32,77224,Rita Pavone,El Partido de Fútbol,Rita Pavone canta en Espanol (Singles Collection),album,2000,Pop,132
33,77224,Rita Pavone,Che Sara (Peppino Di Capri) (Live),Le Canzoni di Rita Pavone,colaboracion,1961,Pop,132
34,77224,Rita Pavone,Alla mia età,Italian 60s,album,2020,Pop,132
35,77224,Rita Pavone,Lui,31 Grandi Successi,album,2016,Pop,132
36,77224,Rita Pavone,Cuore,Cuore,album,2015,NaN,-1
37,77224,Rita Pavone,Cuore,Rita Pavone canta en Espanol (Singles Collection),album,2000,Pop,132
38,77224,Rita Pavone,Sapore di sale,31 Grandi Successi,album,2016,Pop,132
39,77224,Rita Pavone,Abbiamo 16 anni,31 Grandi Successi,album,2016,Pop,132
40,77224,Rita Pavone,Viva La Pappa Col Pomodoro,Rita Pavone canta en Espanol (Singles Collection),album,2000,Pop,132
41,77224,Rita Pavone,Questo nostro amore,Il geghegè e altri successi (Flashback 2011),album,2026,Pop,132
42,77224,Rita Pavone,La partita di pallone,Rita Pavone - I Miei Grandi Successi,album,2024,Pop,132
43,77224,Rita Pavone,No Hay Otro Como Tu (Come Te Non C'è Nessuno),No Hay Otro Como Tu,ep,2015,Pop,132
44,77224,Rita Pavone,Arrivederci Hans,Ihre größten Hits,album,2026,Pop,132
45,77224,Rita Pavone,Come Te Non C'e Nessuno,Rita Pavone,album,2015,Pop,132
46,77224,Rita Pavone,Como te non c’e’ nessuno,Cuore,album,2015,NaN,-1
47,77224,Rita Pavone,If I Had a Hammer,Cuore,album,2015,NaN,-1
48,77224,Rita Pavone,La partita di pallone,Cuore,album,2015,NaN,-1
49,77224,Rita Pavone,Sul cucuzzolo,Cuore,album,2015,NaN,-1

In [17]:
df_artista.to_csv("rita.csv", index=False)

In [18]:
def conseguir_canciones(artist_name, limit=50):     # Función para conseguir 50 canciones de la artista que quieras
    url = "https://api.deezer.com/search"           # URL base de la API para buscar
    params = {                                      # Para insertar los parámetros de la búsqueda
        "q": f'artist:"{artist_name}"',             # La API busca artista por q
        "limit": limit                              # Limit sirve para que saque solo 50
    }
    try:                                            # Bloque try/excep para llamar a la API y que nos dé el resultado
        response = requests.get(url, params=params)
        if response.status_code != 200:
            print("Error en la llamada a Deezer:", response.status_code)    # Si falla lo va a informar
            return pd.DataFrame([])                                         # Y también nos va a devolver el DF vacío
        data = response.json()                                              # Si no falla da la respuesta en json
    except Error as e:
        print("Error en la llamada a Deezer:", e)                           # Para que nos diga exactamente cuál es el error
        return pd.DataFrame([])

    canciones = data.get("data", [])                # Obtiene la lista de canciones
    lista_canciones = []                            # Lista donde se van a acumular las filas para el DF final

    for cancion in canciones:                       # Bucle para que itere con todas las canciones y nos vaya dando los datos
        track_id = cancion["id"]                    # Nos da el id de la canción
        track = requests.get(f"https://api.deezer.com/track/{track_id}").json()  # Pide todos los datos que estén en track
        album = requests.get(f"https://api.deezer.com/album/{track['album']['id']}").json() # Pide todos los datos que estén en album

        genre_id = album.get("genre_id")   # Extrae el ID del género de album
        genre_name = None                  # Creamos la variable "vacía"
        if album.get("genres") and album["genres"].get("data"):   # Le decimoa que en el caso de que genres exista en album
            genre_name = album["genres"]["data"][0].get("name")   # Entonces nos diga el primer género que aparezca (por si hay varios)

        tracks_type = "colaboracion" if len(track.get("contributors", [])) > 1 else album.get("record_type", "track")
        # Buscamos colaboraciones. Para ello, si en contributor aparece más de 1, entonces se trata de una colaboración
        # Si no, le decimos que nos ponga lo que aparezca en record_type que es single o album, y si no que ponga track
        release_year = track.get("release_date", "")[:4] if track.get("release_date") else None
        # Obtiene el año de lanzamiento solo si hay 4 cifras, si no pondrá None 
        lista_canciones.append({                   # Creamos un diccionario para añadir todos los datos que necesitamos
            "id_artista": 85766522,
            "nombre_artista": artist_name,
            "titulo_cancion": track["title"],
            "titulo_album": track["album"]["title"],
            "tipo": tracks_type,
            "año_lanzamiento": release_year,
            "genero": genre_name,
            "id_genero": genre_id,
        })

    return pd.DataFrame(lista_canciones)        # Hacemos que nos devuelta el resultado en un DF

df_artista = conseguir_canciones("Karina", limit=50)
df_artista

,id_artista,nombre_artista,titulo_cancion,titulo_album,tipo,año_lanzamiento,genero,id_genero
0,85766522,Karina,Otoño Porteño,"Musica Porteña, Il Tango di Astor Piazzolla",colaboracion,2012,Tango,73
1,85766522,Karina,Jacinto Chiclana,"Musica Porteña, Il Tango di Astor Piazzolla",colaboracion,2012,Tango,73
2,85766522,Karina,Milonga de la Anunciaciòn,"Musica Porteña, Il Tango di Astor Piazzolla",colaboracion,2012,Tango,73
3,85766522,Karina,Crazy in Love (Electro Swing Version),The Best of Swing Republic,colaboracion,2018,Electro,106
4,85766522,Karina,El baúl de los recuerdos (2015 Remastered Vers...,Éxitos de 1970. Artistas Originales (Remastere...,album,2015,Pop,132
5,85766522,Karina,Satisfeito,Universo Ao Meu Redor,album,2006,Música Brasileña,75
6,85766522,Karina,SINVERGÜENZA - con Angela Torres,SINVERGÜENZA - con Angela Torres,colaboracion,2023,Latino,197
7,85766522,Karina,Rebota,Rebota,colaboracion,2025,Latino,197
8,85766522,Karina,Sé Cómo Duele,Serie 32 Grandes Éxitos,album,2022,Latino,197
9,85766522,Karina,LADRON,LADRON,colaboracion,2025,Latino,197
10,85766522,Karina,Bombon,Bombon,colaboracion,2024,Pop,132
11,85766522,Karina,Con la Misma Moneda,Con la Misma Moneda,album,2010,NaN,-1
12,85766522,Karina,Banana,Banana,colaboracion,2025,Latino,197
13,85766522,Karina,VUELVES TRISTE,QUIMERA,colaboracion,2025,Pop,132
14,85766522,Karina,A Quién,La Colección,album,1990,Latino,197
15,85766522,Karina,Tenemos Razón,Tenemos Razón,colaboracion,2020,Alternativo,85
16,85766522,Karina,Envidiosa (de la serie de Netflix),Envidiosa (de la serie de Netflix),single,2025,Películas/Juegos,173
17,85766522,Karina,Se Como Duele,Siempre Karina,album,2011,Pop,132
18,85766522,Karina,TO-TO,TO-TO,colaboracion,2024,Latino,197
19,85766522,Karina,Meu Nego,Saudade,colaboracion,2022,Electro,106
20,85766522,Karina,Keiner so wie du,Keiner so wie du,colaboracion,2025,Electro,106
21,85766522,Karina,I'm Today (Nefer Song),Mummies (Original Motion Picture Soundtrack),colaboracion,2023,Películas/Juegos,173
22,85766522,Karina,Jamás Vas a Decirle,Miénteme,album,2005,NaN,-1
23,85766522,Karina,Y Es Que Llegaste Tú (En Vivo Desde México D.F...,Grandiosas (En Vivo Desde México D.F./2014),colaboracion,2015,Pop,132
24,85766522,Karina,"Ma ligne de chance (Bande originale du film ""P...",Pierrot le fou (Bande originale du film),album,2021,Películas/Juegos,173
25,85766522,Karina,Inocente (En Vivo en el Luna Park),Inocente (En Vivo en el Luna Park),colaboracion,2022,Latino,197
26,85766522,Karina,Ya Te Olvide,Mujeres,album,2017,NaN,-1
27,85766522,Karina,cold and lost,cold and lost,single,2026,Electro,106
28,85766522,Karina,A quién le importa (Latin Pride Version by Jua...,A quién le importa,colaboracion,2023,Pop,132
29,85766522,Karina,Frágil,Frágil,colaboracion,2023,Cumbia,71
30,85766522,Karina,Corazon Mentiroso,Sin Vergüenza,album,2009,Latino,197
31,85766522,Karina,Díganle,Con la Misma Moneda,album,2010,NaN,-1
32,85766522,Karina,New Song (Spanish Version),Mummies (Original Motion Picture Soundtrack),colaboracion,2023,Películas/Juegos,173
33,85766522,Karina,A Quien,Siempre Karina,album,2011,Pop,132
34,85766522,Karina,Show Me Love feat. Karina Chavez (Safari Radio...,Show Me Love,colaboracion,2007,Electro,106
35,85766522,Karina,Paisaje (En Vivo),ODISEA (En Vivo),colaboracion,2025,Cumbia,71
36,85766522,Karina,Marions-nous au soleil,La belle étoile,colaboracion,2009,Rock,152
37,85766522,Karina,Do Pilà,Straight from the Decks (Guts Finest Selection...,colaboracion,2019,Rock,152
38,85766522,Karina,No Me Digas Que No,No Me Digas Que No,colaboracion,2022,Cumbia,71
39,85766522,Karina,Te Arrepentirás (feat. Karina & La Joaqui),Te Arrepentirás (feat. Karina & La Joaqui),colaboracion,2022,NaN,-1
40,85766522,Karina,New Song,Mummies (Original Motion Picture Soundtrack),colaboracion,2023,Películas/Juegos,173
41,85766522,Karina,Nos Dois,Saudade,colaboracion,2022,Electro,106
42,85766522,Karina,Paisaje,Paisaje,colaboracion,2021,Latino,197
43,85766522,Karina,Karina (Mix En Vivo),Karina (Mix En Vivo),colaboracion,2026,Pop,132
44,85766522,Karina,¡Oh! Carol,Grandes Exitos,album,2003,Pop,132
45,85766522,Karina,El Baúl de los Recuerdos,El Baúl de los Recuerdos y todos sus Exitos,album,1989,Pop,132
46,85766522,Karina,tired of me,tired of me,single,2021,Pop,132
47,85766522,Karina,A Esa (En Vivo),Luna Park 2015,colaboracion,2015,Cumbia,71

In [19]:
df_artista.to_csv("karina.csv", index=False)

In [20]:
def conseguir_canciones(artist_name, limit=50):     # Función para conseguir 50 canciones de la artista que quieras
    url = "https://api.deezer.com/search"           # URL base de la API para buscar
    params = {                                      # Para insertar los parámetros de la búsqueda
        "q": f'artist:"{artist_name}"',             # La API busca artista por q
        "limit": limit                              # Limit sirve para que saque solo 50
    }
    try:                                            # Bloque try/excep para llamar a la API y que nos dé el resultado
        response = requests.get(url, params=params)
        if response.status_code != 200:
            print("Error en la llamada a Deezer:", response.status_code)    # Si falla lo va a informar
            return pd.DataFrame([])                                         # Y también nos va a devolver el DF vacío
        data = response.json()                                              # Si no falla da la respuesta en json
    except Error as e:
        print("Error en la llamada a Deezer:", e)                           # Para que nos diga exactamente cuál es el error
        return pd.DataFrame([])

    canciones = data.get("data", [])                # Obtiene la lista de canciones
    lista_canciones = []                            # Lista donde se van a acumular las filas para el DF final

    for cancion in canciones:                       # Bucle para que itere con todas las canciones y nos vaya dando los datos
        track_id = cancion["id"]                    # Nos da el id de la canción
        track = requests.get(f"https://api.deezer.com/track/{track_id}").json()  # Pide todos los datos que estén en track
        album = requests.get(f"https://api.deezer.com/album/{track['album']['id']}").json() # Pide todos los datos que estén en album

        genre_id = album.get("genre_id")   # Extrae el ID del género de album
        genre_name = None                  # Creamos la variable "vacía"
        if album.get("genres") and album["genres"].get("data"):   # Le decimoa que en el caso de que genres exista en album
            genre_name = album["genres"]["data"][0].get("name")   # Entonces nos diga el primer género que aparezca (por si hay varios)

        tracks_type = "colaboracion" if len(track.get("contributors", [])) > 1 else album.get("record_type", "track")
        # Buscamos colaboraciones. Para ello, si en contributor aparece más de 1, entonces se trata de una colaboración
        # Si no, le decimos que nos ponga lo que aparezca en record_type que es single o album, y si no que ponga track
        release_year = track.get("release_date", "")[:4] if track.get("release_date") else None
        # Obtiene el año de lanzamiento solo si hay 4 cifras, si no pondrá None 
        lista_canciones.append({                   # Creamos un diccionario para añadir todos los datos que necesitamos
            "id_artista": track["artist"]["id"],
            "nombre_artista": artist_name,
            "titulo_cancion": track["title"],
            "titulo_album": track["album"]["title"],
            "tipo": tracks_type,
            "año_lanzamiento": release_year,
            "genero": genre_name,
            "id_genero": genre_id,
        })

    return pd.DataFrame(lista_canciones)        # Hacemos que nos devuelta el resultado en un DF

df_artista = conseguir_canciones("Massiel", limit=50)
df_artista

,id_artista,nombre_artista,titulo_cancion,titulo_album,tipo,año_lanzamiento,genero,id_genero
0,54310142,Massiel,"Me Dijeron (feat. DVG, Magdiel CRZ, Risen, Lir...","Me Dijeron (feat. DVG, Magdiel CRZ, Risen, Lir...",colaboracion,2023,Rap/Hip Hop,116
1,105903,Massiel,Sur Fond De Marseillaise,Demain c'est toi,album,2005,Rap/Hip Hop,116
2,10396026,Massiel,Un Mundo Feliz,Manual de Belleza,colaboracion,2026,Pop latino,138
3,65759,Massiel,"Berlioz: Hymne des Marseillais, H 51a",Plácido Domingo - Artist Portrait 2007,colaboracion,2004,Clásica,98
4,129722,Massiel,Eres,Lo Mejor de Massiel,album,2013,Pop,132
5,129722,Massiel,El amor,Lo Mejor de Massiel,album,2013,Pop,132
6,129722,Massiel,"La, La, La",Lo Mejor de Massiel,album,2015,Pop,132
7,129722,Massiel,El amor (en directo),Massiel En Des. Concierto,album,2014,Pop,132
8,129722,Massiel,Brindaremos por él,Lo Mejor de Massiel,album,2013,Pop,132
9,129722,Massiel,El Noa-Noa,Lo Mejor de Massiel,album,2013,Pop,132
10,129722,Massiel,Rosas en el Mar,Cuentame,album,2001,Pop,132
11,64956,Massiel,Volver a los 17 (feat. Massiel),Rosa se esta buscando en el espejo,colaboracion,2010,Niños,95
12,355785,Massiel,El Credo,Aromas de Libertad (Son Tus Perjúmenes Mujer),colaboracion,2007,Folk,466
13,129722,Massiel,Más fuerte,iCollection,album,2016,Pop,132
14,129722,Massiel,Aleluya No. 1,Orígenes,album,2018,Pop,132
15,129722,Massiel,"La, La, La (Remix)",Massiel: Sus Grandes Éxitos,album,2002,Pop,132
16,129722,Massiel,Otra mujer,Corazón de hierro,album,2014,Pop,132
17,129722,Massiel,"La, la, la (en directo)",Massiel En Des. Concierto,album,2014,Pop,132
18,129722,Massiel,Deja la Flor,Orígenes,album,2018,Pop,132
19,129722,Massiel,Marinero (Marinaio),Corazón de hierro,album,2014,Pop,132
20,129722,Massiel,Jenny la de los piratas (remastered),Masiel Canta Bertolt Brecht,album,2005,Clásica,98
21,129722,Massiel,Te amo,Lo Mejor de Massiel,album,2013,Pop,132
22,129722,Massiel,Lady Veneno,Lo Mejor de Massiel,album,2013,Pop,132
23,129722,Massiel,Rufo el Pescador,Orígenes,album,2018,Pop,132
24,129722,Massiel,Canción de la moldavia (remastered),Masiel Canta Bertolt Brecht,album,2005,Clásica,98
25,129722,Massiel,Mañana será,Tiempos dificiles,album,2014,Pop,132
26,129722,Massiel,Basta de peleas,Corazón de hierro,album,2014,Pop,132
27,129722,Massiel,Balada de maría sanders (remastered),Masiel Canta Bertolt Brecht,album,2005,Clásica,98
28,129722,Massiel,Amén,Orígenes,album,2018,Pop,132
29,129722,Massiel,Sola en libertad,A Tí Mujer,album,2020,Pop,132
30,14385933,Massiel,Lies,Lies,colaboracion,2018,Electro,106
31,129722,Massiel,La la La (En Vivo),"Idolos Latinos en Vivo, Vol. 2",compile,2015,Pop,132
32,129722,Massiel,Brindaremos por El (En Vivo),En Vina en Vivo,album,2016,Pop,132
33,129722,Massiel,Eres (En Vivo),En Vina en Vivo,album,2016,Pop,132
34,129722,Massiel,Marinero (En Vivo),En Vina en Vivo,album,2016,Pop,132
35,129722,Massiel,Más Fuerte Que el Viento (En Vivo),En Vina en Vivo,album,2016,Pop,132
36,129722,Massiel,Rosas en el Mar (En Vivo),En Vina en Vivo,album,2016,Pop,132
37,4155433,Massiel,Noche De Paz Tropical,It's a Tropical Christmas,colaboracion,2007,NaN,-1
38,1347694,Massiel,Barquito mío,Una Voz,album,2011,Latino,197
39,1347694,Massiel,Gaspar en la noche,Una Voz,album,2011,Latino,197
40,1347694,Massiel,Coda - A pasitos pequeños,Una Voz,album,2011,Latino,197
41,123242282,Massiel,Butterfly (feat. Massiel) (Live),Raw Talent Live The Soundtrack Las Vegas,colaboracion,2008,Pop,132
42,129722,Massiel,Acordeón,iCollection,album,2016,Pop,132
43,129722,Massiel,Todo lo que cambié por ti,iCollection,album,2016,Pop,132
44,129722,Massiel,Voy a empezar de nuevo,iCollection,album,2016,Pop,132
45,129722,Massiel,Miradas de amor,iCollection,album,2016,Pop,132
46,129722,Massiel,Tiempos difíciles,iCollection,album,2016,Pop,132
47,129722,Massiel,Quiero amarte hasta el fondo de mi corazón,iCollection,album,2016,Pop,132
48,129722,Massiel,Déjame,iCollection,album,2016,Pop,132
49,129722,Massiel,Poco después de las doce de un veinte de marzo,iCollection,album,2016,Pop,132

In [21]:
df_artista.to_csv("massiel.csv", index=False)

In [5]:
LASTFM_API_KEY = "88d4c2ca98c2eacf39cbd94fdd2a63ba"

In [ ]:
def obtener_info_lastfm(artist_name):
    
    LASTFM_BASE_URL = "https://ws.audioscrobbler.com/2.0/" #endpoint

    params = {                                             #parámetros para buscar
        "method": "artist.getInfo",
        "artist": artist_name,
        "api_key": LASTFM_API_KEY,
        "format": "json",
        "autocorrect": 1
    }

    data = requests.get(
        LASTFM_BASE_URL,
        params=params
    ).json()

    if "artist" not in data:
        return {
            "nombre_artista": artist_name,
            "biografía": None,
            "listeners": None,
            "playcount": None
        }

    artist = data["artist"]

    return {
        "nombre_artista": artist_name,
        "biografía": artist.get("bio", {}).get("summary"),
        "listeners": artist.get("stats", {}).get("listeners"),
        "playcount": artist.get("stats", {}).get("playcount")
    }
artistas = ["Janis Joplin", "Celia Cruz", "Aretha Franklin", "Lola Flores", "Nina Simone", "Silvie Vartan", "Patty Pravo", "Rita Pavone", "Karina", "Massiel"]

# Obtener info de cada artista
lista_info = [obtener_info_lastfm(artista) for artista in artistas]

# Convertir a DataFrame
df_info = pd.DataFrame(lista_info)
df_info

,artist_name,biography,listeners,playcount
0,Janis Joplin,Janis Joplin (born 19 January 1943 in Port Art...,1937889,34092778
1,Celia Cruz,Celia Cruz (born as Úrsula Hilaria Celia de la...,587427,5043428
2,Aretha Franklin,"Aretha Franklin (March 25, 1942 - August 16, 2...",2932315,53111402
3,Lola Flores,"Lola Flores, ""La Faraona"" born January 21, 192...",43166,351079
4,Nina Simone,Eunice Kathleen Waymon (21 February 1933 – 21 ...,2995908,75195380
5,Silvie Vartan,"Sylvie Vartan (born August 15, 1944 in Iskretz...",206481,1944467
6,Patty Pravo,"Patty Pravo (born Nicoletta Strambelli, 9 Apri...",113871,1015532
7,Rita Pavone,"Rita Pavone (born August 23, 1945 - Turin) is ...",77769,554641
8,Karina,There are multiple artists with this name:\n\n...,140669,1869320
9,Massiel,Massiel (real name Maria de los Angeles Santam...,39865,234507

In [9]:
df_info.to_csv("informacion_artist.csv", index=False)

In [10]:
df_info.to_csv("artist_similares", index=False)

In [ ]:
import glob

archivos = glob.glob("*.csv")
artista_completo_Teresa = pd.concat([pd.read_csv(f) for f in archivos], ignore_index=True)
artista_completo_Teresa.to_csv("artista_completo_Teresa.csv", index=False, encoding="utf-8")

In [6]:
import requests
import pandas as pd

LASTFM_BASE_URL = "https://ws.audioscrobbler.com/2.0/"

def obtener_info_lastfm(artist_name):
    params = {
        "method": "artist.getInfo",
        "artist": artist_name,
        "api_key": LASTFM_API_KEY,
        "format": "json",
        "autocorrect": 1
    }

    data = requests.get(LASTFM_BASE_URL, params=params).json()

    if "artist" not in data:
        return {
            "nombre_artista": artist_name,
            "biografía": None,
            "listeners": None,
            "playcount": None
        }

    artist = data["artist"]

    return {
        "nombre_artista": artist_name,
        "biografía": artist.get("bio", {}).get("summary"),
        "listeners": artist.get("stats", {}).get("listeners"),
        "playcount": artist.get("stats", {}).get("playcount")
    }


def obtener_artistas_similares(artist_name):
    params = {
        "method": "artist.getSimilar",
        "artist": artist_name,
        "api_key": LASTFM_API_KEY,
        "format": "json",
        "autocorrect": 1,
        "limit": 10
    }

    data = requests.get(LASTFM_BASE_URL, params=params).json()

    if "similarartists" not in data:
        return []

    return [
        artista["name"]
        for artista in data["similarartists"]["artist"]
    ]


artistas = ["Janis Joplin", "Celia Cruz", "Aretha Franklin", "Lola Flores", "Nina Simone",
            "Silvie Vartan", "Patty Pravo", "Rita Pavone", "Karina", "Massiel"]

lista_info = [obtener_info_lastfm(artista) for artista in artistas]
lista_similares = [obtener_artistas_similares(artista) for artista in artistas]


df_info = pd.DataFrame(lista_info)

df_similares = pd.DataFrame({
    "nombre_artista": artistas,
    "artistas_similares": lista_similares
})


df_completo = pd.merge(df_info, df_similares, on="nombre_artista", how="left")
df_completo

,nombre_artista,biografía,listeners,playcount,artistas_similares
0,Janis Joplin,Janis Joplin (born 19 January 1943 in Port Art...,1937889,34092778,"[Big Brother & The Holding Company, Jimi Hendr..."
1,Celia Cruz,Celia Cruz (born as Úrsula Hilaria Celia de la...,587427,5043428,"[Johnny Pacheco, Marc Anthony, Oscar D'León, R..."
2,Aretha Franklin,"Aretha Franklin (March 25, 1942 - August 16, 2...",2932315,53111402,"[Etta James, Gladys Knight & The Pips, Roberta..."
3,Lola Flores,"Lola Flores, ""La Faraona"" born January 21, 192...",43166,351079,"[Rocío Jurado, Camarón de la Isla, Isabel Pant..."
4,Nina Simone,Eunice Kathleen Waymon (21 February 1933 – 21 ...,2995908,75195380,"[Billie Holiday, Aretha Franklin, Etta James, ..."
5,Silvie Vartan,"Sylvie Vartan (born August 15, 1944 in Iskretz...",206481,1944467,"[Sheila, Françoise Hardy, Brigitte Bardot, Gil..."
6,Patty Pravo,"Patty Pravo (born Nicoletta Strambelli, 9 Apri...",113871,1015532,"[Anna Oxa, Mina, Loredana Bertè, Marcella Bell..."
7,Rita Pavone,"Rita Pavone (born August 23, 1945 - Turin) is ...",77769,554641,"[Edoardo Vianello, Little Tony, Peppino Di Cap..."
8,Karina,There are multiple artists with this name:\n\n...,140669,1869320,"[Cazzu, NINGNING, Emilia, Ha*Ash, Amanda Migue..."
9,Massiel,Massiel (real name Maria de los Angeles Santam...,39865,234507,"[Mari Trini, Rocío Jurado, Paloma San Basilio,..."

In [7]:
df_completo.to_csv("last_fm.csv", index=False)

In [23]:
import pandas as pd
import glob

ruta = "./concatenar/"
archivos = [f for f in glob.glob(ruta + "*.csv") if "artista_completo" not in f]
print("Archivos encontrados:", archivos)

artista_completo = pd.concat([pd.read_csv(f) for f in archivos], ignore_index=True)
artista_completo.to_csv(ruta + "artista_completo.csv", index=False, encoding="utf-8")

print(f"Filas totales: {len(artista_completo)}")

Archivos encontrados: ['./concatenar\\aretha.csv', './concatenar\\celia.csv', './concatenar\\janis.csv', './concatenar\\karina.csv', './concatenar\\lola.csv', './concatenar\\massiel.csv', './concatenar\\nina.csv', './concatenar\\patty.csv', './concatenar\\rita.csv', './concatenar\\silvie.csv']
Filas totales: 454

In [24]:
print(archivos, "\n")

['./concatenar\\aretha.csv', './concatenar\\celia.csv', './concatenar\\janis.csv', './concatenar\\karina.csv', './concatenar\\lola.csv', './concatenar\\massiel.csv', './concatenar\\nina.csv', './concatenar\\patty.csv', './concatenar\\rita.csv', './concatenar\\silvie.csv']

In [5]:
artista_completo

,id_artista,nombre_artista,titulo_cancion,titulo_album,tipo,año_lanzamiento,genero,id_genero
0,744,Nina Simone,I Put A Spell On You,I Put A Spell On You,album,2018,Jazz,129
1,744,Nina Simone,Feeling Good,Feeling Good: The Very Best Of Nina Simone,album,2019,Jazz,129
2,744,Nina Simone,Ain't Got No - I Got Life (From the Musical Pr...,The Greatest Hits,album,2003,Pop,132
3,744,Nina Simone,Sinnerman,Feeling Good: The Very Best Of Nina Simone,album,2019,Jazz,129
4,744,Nina Simone,My Baby Just Cares for Me,My Baby Just Cares for Me,album,2009,Jazz,129
...,...,...,...,...,...,...,...,...
485,129722,Massiel,Todo lo que cambié por ti,iCollection,album,2016,Pop,132
486,129722,Massiel,Voy a empezar de nuevo,iCollection,album,2016,Pop,132
487,129722,Massiel,Miradas de amor,iCollection,album,2016,Pop,132
488,129722,Massiel,Tiempos difíciles,iCollection,album,2016,Pop,132
489,129722,Massiel,Quiero amarte hasta el fondo de mi corazón,iCollection,album,2016,Pop,132

In [7]:
artista_completo["nombre_artista"].unique()

<StringArray>
[                                   'Nina Simone',
                                     'Celia Cruz',
                                   'Ricky Martin',
                                 'Johnny Pacheco',
       'Celia Cruz, Rene Hernandez Y Su Orquesta',
                                 'Jarabe de Palo',
                                 'Gloria Estefan',
                            'La Sonora Matancera',
                                  'Gente De Zona',
                                    'Tony Succar',
                                   'Willie Colón',
              'Big Brother & The Holding Company',
                                   'Janis Joplin',
                    'Paul Butterfield Blues Band',
 'Big Brother & The Holding Company;Janis Joplin',
                'Various Artists - Kobra Records',
                                        'Señor F',
                                 'Rodrigo Cuevas',
                                     'Marshmello',
                                'Plácido Domingo',
                                        'Massiel',
        'Carlos Mejía Godoy y los de Palacagüina',
                                      'Rosa Leon',
                                        'MASSIEL',
                                    'Last & Loud',
                                   'David Montes',
                                 'Massiel Yanira',
                             'Dancing Ritmo Crew']
Length: 28, dtype: str

In [1]:
import os

ruta = "C:/Users/Teresa/Desktop/Adalab/proyectos/proyectos_grupo/proyecto2/concatenar/"

archivos = os.listdir(ruta)
print(f"Tienes {len(archivos)} archivos:")
for f in archivos:
    print(" -", f)

Tienes 10 archivos:
 - aretha.csv
 - celia.csv
 - janis.csv
 - karina.csv
 - lola.csv
 - massiel.csv
 - nina.csv
 - patty.csv
 - rita.csv
 - silvie.csv

In [2]:
import pandas as pd
import glob

ruta = "C:/Users/Teresa/Desktop/Adalab/proyectos/proyectos_grupo/proyecto2/concatenar/"

archivos = [f for f in glob.glob(ruta + "*.csv") if "artista_completo" not in f]
print("Archivos encontrados:", archivos)

artista_completo = pd.concat([pd.read_csv(f) for f in archivos], ignore_index=True)
artista_completo.to_csv(ruta + "artista_completo.csv", index=False, encoding="utf-8")

print(f"Filas totales: {len(artista_completo)}")

Archivos encontrados: ['C:/Users/Teresa/Desktop/Adalab/proyectos/proyectos_grupo/proyecto2/concatenar\\aretha.csv', 'C:/Users/Teresa/Desktop/Adalab/proyectos/proyectos_grupo/proyecto2/concatenar\\celia.csv', 'C:/Users/Teresa/Desktop/Adalab/proyectos/proyectos_grupo/proyecto2/concatenar\\janis.csv', 'C:/Users/Teresa/Desktop/Adalab/proyectos/proyectos_grupo/proyecto2/concatenar\\karina.csv', 'C:/Users/Teresa/Desktop/Adalab/proyectos/proyectos_grupo/proyecto2/concatenar\\lola.csv', 'C:/Users/Teresa/Desktop/Adalab/proyectos/proyectos_grupo/proyecto2/concatenar\\massiel.csv', 'C:/Users/Teresa/Desktop/Adalab/proyectos/proyectos_grupo/proyecto2/concatenar\\nina.csv', 'C:/Users/Teresa/Desktop/Adalab/proyectos/proyectos_grupo/proyecto2/concatenar\\patty.csv', 'C:/Users/Teresa/Desktop/Adalab/proyectos/proyectos_grupo/proyecto2/concatenar\\rita.csv', 'C:/Users/Teresa/Desktop/Adalab/proyectos/proyectos_grupo/proyecto2/concatenar\\silvie.csv']
Filas totales: 498

In [12]:
## Conexión a Mysql
def conexion_mysql():
    try:
        conexion = mysql.connector.connect(
             host = '127.0.0.1',
             user = 'root',
             password = 'guitarra'
        )
        print("Conexion exitosa")
        return conexion
    except Exception as e:
        print(f"Error al conectar: {e}")
        
conexion = conexion_mysql()

Conexion exitosa

In [13]:
cursor = conexion.cursor()

In [8]:
#Creación Base de Datos

try:
    cursor = conexion.cursor()
    query_crear_bbdd = """
    CREATE DATABASE IF NOT EXISTS musicstream
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci
    """
    cursor.execute(query_crear_bbdd)
    print("Query existosa")
except Error as e:
    print(e)

Query existosa

In [9]:
cursor.execute("use musicstream")
query_crear_tabla = '''CREATE TABLE artistas (
                        id_artista INT PRIMARY KEY AUTO_INCREMENT, 
                        nombre_artista VARCHAR(50) NOT NULL
                        );'''
cursor.execute(query_crear_tabla)
print ("Tabla creada correctamente")

Tabla creada correctamente

In [17]:
cursor.execute("USE musicstream")

In [16]:
df_tabla_artistas = pd.read_csv(r"C:/Users/Teresa/Desktop/Adalab/proyectos/proyectos_grupo/proyecto2/git_teresa/proyecto-da-promo-67-modulo2-team-3/Deezer/artistas_completo_deezer.csv",
    encoding="utf-8"
)
df_tabla_artistas = df_tabla_artistas[["nombre_artista"]].drop_duplicates()
for index, fila in df_tabla_artistas.iterrows():
    query_insert = """
    INSERT INTO artistas (nombre_artista)
    VALUES (%s)
    """
    valores = (fila["nombre_artista"],)
    cursor.execute(query_insert, valores)
conexion.commit()
print("Datos insertados correctamente")

Datos insertados correctamente

In [ ]:
ruta = "C:/Users/Teresa/Desktop/Adalab/proyectos/proyectos_grupo/proyecto2/concatenar/"

In [5]:
print(os.listdir())

['.git', '.gitignore', 'Deezer', 'divas_inic.ipynb', 'LFM', 'README.md']

In [18]:
cursor.execute("use musicstream")
query_crear_tabla = """
CREATE TABLE canciones (
    id_cancion INT PRIMARY KEY AUTO_INCREMENT,
    id_artista INT NOT NULL,
    titulo_cancion VARCHAR(300) NOT NULL,
    titulo_album VARCHAR(300),
    tipo VARCHAR(100),
    año_lanzamiento INT,
    genero VARCHAR(100),
    id_genero FLOAT,
    FOREIGN KEY (id_artista)
    REFERENCES artistas(id_artista)
);
"""
cursor.execute(query_crear_tabla)
print("Tabla canciones creada correctamente")

Tabla canciones creada correctamente

In [19]:
df_tabla_canciones = pd.read_csv(r"C:/Users/Teresa/Desktop/Adalab/proyectos/proyectos_grupo/proyecto2/git_teresa/proyecto-da-promo-67-modulo2-team-3/Deezer/artistas_completo_deezer.csv",
    encoding="utf-8"
)
for index, fila in df_tabla_canciones.iterrows():
    query_id_artista = """
    SELECT id_artista
    FROM artistas
    WHERE nombre_artista = %s
    """
    cursor.execute(
        query_id_artista,
        (fila["nombre_artista"],)
    )
    resultado = cursor.fetchone()
    id_artista = resultado[0]
    query_insert = """
    INSERT INTO canciones (
        id_artista,
        titulo_cancion,
        titulo_album,
        tipo,
        año_lanzamiento,
        genero,
        id_genero
    )
    VALUES (%s, %s, %s, %s, %s, %s, %s)
    """
    valores = (
        id_artista,
        fila["titulo_cancion"],
        fila["titulo_album"],
        fila["tipo"],
        fila["año_lanzamiento"],
        fila["genero"]
        if pd.notna(fila["genero"])
        else None,
        fila["id_genero"]
        if pd.notna(fila["id_genero"])
        else None
    )
    cursor.execute(query_insert, valores)
conexion.commit()
print("Datos insertados correctamente")

Datos insertados correctamente

In [20]:
query_crear_tabla = """
CREATE TABLE informacion_artistas (
    id_info INT PRIMARY KEY AUTO_INCREMENT,
    id_artista INT NOT NULL,
    nombre_artista VARCHAR(50),
    biografia TEXT,
    listeners BIGINT,
    playcount BIGINT,
    artistas_similares TEXT,
    FOREIGN KEY (id_artista)
    REFERENCES artistas(id_artista)
);
"""
cursor.execute(query_crear_tabla)
print("Tabla informacion_artistas creada correctamente")

Tabla informacion_artistas creada correctamente

In [23]:
df_lfm = pd.read_csv(r"C:/Users/Teresa/Desktop/Adalab/proyectos/proyectos_grupo/proyecto2/git_teresa/proyecto-da-promo-67-modulo2-team-3/LFM/artistas_completo_LFM.csv",
    encoding="utf-8"
)
for index, fila in df_lfm.iterrows():
    query_id_artista = """
    SELECT id_artista
    FROM artistas
    WHERE nombre_artista = %s
    """
    cursor.execute(
        query_id_artista,
        (fila["nombre_artista"],)
    )
    resultado = cursor.fetchone()
    id_artista = resultado[0]
    query_insert = """
    INSERT INTO informacion_artistas (
        id_artista,
        nombre_artista,
        biografia,
        listeners,
        playcount,
        artistas_similares
    )
    VALUES (%s, %s, %s, %s, %s, %s)
    """
    valores = (
        id_artista,
        fila["nombre_artista"],
        fila["biografia"],
        fila["listeners"],
        fila["playcount"],
        fila["artistas_similares"]
    )
    cursor.execute(query_insert, valores)
conexion.commit()
print("Datos insertados correctamente")

TypeError: 'NoneType' object is not subscriptable

In [ ]:
#Rocio
for index, fila in df_last.iterrows():
    query_id_artista = """
    SELECT id_artista
    FROM artistas
    WHERE nombre_artista = %s
    """
    cursor.execute(
        query_id_artista,
        (fila["nombre_artista"],)
    )
    resultado = cursor.fetchone()
    if resultado is None:
        print(f"Artista no encontrado: {fila['nombre_artista']}")
        continue

    id_artista = resultado[0]
    query_insert = """
    INSERT INTO informacion_artistas (
        id_artista,
        nombre_artista,
        biografia,
        listeners,
        playcount,
        artistas_similares
    )
    VALUES (%s, %s, %s, %s, %s, %s)
    """
    valores = (
        id_artista,
        fila["nombre_artista"],
        fila["biografia"],
        fila["listeners"],
        fila["playcount"],
        fila["artistas_similares"]
    )
    cursor.execute(query_insert, valores)
connection.commit()
print("Datos insertados correctamente")